Repository rook/rook, pull requests merged in 2021-11, with the labels that each got.

#9080 rgw: change the way to livenessProbe and introduce readinessProbe
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  cluster/examples/kubernetes/ceph/object-ec.yaml
  cluster/examples/kubernetes/ceph/object-openshift.yaml
  cluster/examples/kubernetes/ceph/object.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/config/livenessprobe.go
  pkg/operator/ceph/config/livenessprobe_test.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  tests/integration/ceph_base_object_test.go
Labels: backport, ceph-rgw

#9091 rbd-mirror: use a sorted list for peer token content
  pkg/daemon/ceph/client/mirror.go
Labels: backport-release-1.7

#9098 core: Allow downgrade of all daemons consistently
  pkg/operator/ceph/cluster/version.go
  pkg/operator/ceph/cluster/version_test.go
Labels: upgrade, backport-release-1.7

#9112 Revert "ci: trigger push build action after tag creation"
  .github/workflows/push-build.yaml
Labels: backport-release-1.7

#8426 ceph: support bucket notifications for object storage
  Documentation/ceph-object-bucket-notifications.md
  PendingReleaseNotes.md
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/bucket-notification-endpoint.yaml
  cluster/examples/kubernetes/ceph/bucket-notification.yaml
  cluster/examples/kubernetes/ceph/bucket-topic.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  cluster/examples/kubernetes/ceph/object-bucket-claim-notification.yaml
  design/ceph/object/ceph-bucket-notification-crd.md
  pkg/apis/ceph.rook.io/v1/notification.go
  pkg/apis/ceph.rook.io/v1/notification_test.go
  pkg/apis/ceph.rook.io/v1/register.go
  pkg/apis/ceph.rook.io/v1/topic.go
  pkg/apis/ceph.rook.io/v1/topic_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephbucketnotification.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephbuckettopic.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_cephbucketnotification.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_cephbuckettopic.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/generated_expansion.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/cephbucketnotification.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/cephbuckettopic.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/ceph.rook.io/v1/cephbucketnotification.go
  pkg/client/listers/ceph.rook.io/v1/cephbuckettopic.go
  pkg/client/listers/ceph.rook.io/v1/expansion_generated.go
  pkg/operator/ceph/cluster/dependents.go
  pkg/operator/ceph/cluster/dependents_test.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/notification/s3ext.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/topic/provisioner.go
  tests/framework/clients/bucket.go
  tests/framework/clients/notification.go
  tests/framework/clients/test_client.go
  tests/framework/clients/topic.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_v1.6.go
  tests/integration/ceph_bucket_notification_test.go
Labels: ceph

#9107 pool: Allow more data chunks in an ec pool
  cluster/charts/rook-ceph/templates/resources.yaml
  cluster/examples/kubernetes/ceph/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.7

#8744 ceph: run operator with rook user
  .github/workflows/canary-integration-test.yml
  PendingReleaseNotes.md
  cluster/charts/rook-ceph/templates/deployment.yaml
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  cluster/examples/kubernetes/ceph/operator.yaml
  cluster/examples/kubernetes/ceph/toolbox.yaml
  images/ceph/Dockerfile
  pkg/daemon/ceph/osd/kms/volumes.go
  pkg/daemon/ceph/osd/kms/volumes_test.go
  pkg/operator/ceph/webhook.go
Labels: ceph

#9081 ci: use github composition to reduce duplication
  .github/workflows/canary-integration-test.yml
  .github/workflows/collect-logs/action.yaml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-setup/action.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/setup-cluster-resources/action.yaml
Labels: ci

#9128 helm: Enable cephfs volume expansion by default
  cluster/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  cluster/charts/rook-ceph-cluster/values.yaml
Labels: helm, backport-release-1.7

#9137 rgw: Raise errors when rgw daemon fails to be created
  pkg/operator/ceph/object/rgw.go
Labels: objectstore, backport-release-1.6, backport-release-1.7

#9147 doc: fix ephemeral link for rbd pod
  Documentation/ceph-csi-drivers.md
Labels: docs, backport-release-1.7

#9155 docs: Fix the links from docs to github examples in master branch
  Documentation/branch.liquid
Labels: skip-ci

#8994 security: update auth permissions for external cluster
  cluster/examples/kubernetes/ceph/create-external-cluster-resources.py
Labels: ceph, ceph-external

#9168 core: remove unnecessary option
  cmd/rook/ceph/operator.go
  pkg/util/flags/flags.go
Labels: operator, backport-release-1.7

#9158 osd: set blkdevmapper capabilities
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.7

#9178 docs: generate correct doc links to master github branch
  Documentation/branch.liquid
Labels: skip-ci

#9181 helm: Set correct ingress endpoint protocol
  cluster/charts/rook-ceph-cluster/templates/ingress.yaml
  cluster/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.7

#9191 osd: add privileged support (back) to blkdevmapper securityContext (work-around)
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.7

#9190 docs: remove old commitlint component `ceph` from doc
  Documentation/development-flow.md
Labels: docs, skip-ci, backport-release-1.7

#9203 mon: set cluster name to mon cluster
  pkg/operator/ceph/cluster/cluster.go
Labels: backport-release-1.7

#8579 ceph: add support in RGW to communicate vault with TLS
  .github/workflows/canary-integration-test.yml
  Documentation/ceph-object-store-crd.md
  pkg/daemon/ceph/osd/kms/envs.go
  pkg/daemon/ceph/osd/kms/volumes.go
  pkg/daemon/ceph/osd/kms/volumes_test.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  tests/scripts/deploy-validate-vault.sh
Labels: ceph

#9187 docs: add OMAP quick fix warning to upgrade guide
  Documentation/ceph-upgrade.md
Labels: backport-release-1.6, backport-release-1.7

#9094 pool: file: object: clean up health checkers for both types of deletion
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/pool/controller.go
Labels: backport-release-1.7

#9226 docs: move the test readme to the official doc
  Documentation/development-environment.md
  tests/README.md
Labels: skip-ci

#9180 #8502: Make monitoring object labels overridable
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/apis/ceph.rook.io/v1/labels_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/k8sutil/prometheus_test.go
Labels: backport-release-1.7

#9202 docs: add details about HPA via KEDA
  Documentation/ceph-monitoring.md
  cluster/examples/kubernetes/ceph/monitoring/keda-rgw.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.7

#9224 nfs: only set the pool size when it exists and always run default pool creation
  pkg/daemon/ceph/client/pool.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
Labels: backport-release-1.7

#9243 monitoring: update label on prometheus resources
  pkg/operator/k8sutil/prometheus.go
Labels: backport-release-1.7

#9143 object: fix search user in objectstore
  pkg/operator/ceph/object/objectstore.go
Labels: backport-release-1.7

#9236 core: fix openshift security context
  cluster/examples/kubernetes/ceph/operator-openshift.yaml
  pkg/apis/ceph.rook.io/v1/scc.go
Labels: backport-release-1.7

#8931 test: test rgw multisite nightly
  .github/workflows/canary-integration-test.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/rgw-multisite-test/action.yml
  tests/scripts/github-action-helper.sh
Labels: test, ceph-rgw

#9230 osd: check if osd is safe-to-destroy before removal
  .github/workflows/canary-integration-test.yml
  cluster/examples/kubernetes/ceph/osd-purge.yaml
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/crash.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/osd/remove.go
  tests/scripts/collect-logs.sh
Labels: backport-release-1.7

#9249 object: fix rgw ceph config
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/rgw.go
Labels: backport-release-1.7

#9262 bot: add bot message when pushing on a release branch
  .mergify.yml
Labels: skip-ci

#9264 cephfs-mirror: various fixes for random bootstrap peer import errors
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/filesystem_mirror.go
Labels: backport-release-1.7
