Repository rook/rook, pull requests merged in 2021-12, with the labels that each got.

#8547 csi: mount host's /etc/selinux in node plugins
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: ceph

#9287 helm: addition of mountOptions into storage class configuration
  Documentation/helm-ceph-cluster.md
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.7

#9290 osd: Honor skipUpgradeChecks for OSDs
  pkg/operator/ceph/cluster/osd/update.go
Labels: backport-release-1.8

#9222 docs: add guide doc for flex migration
  Documentation/flex-to-csi-migration.md
  cluster/examples/kubernetes/ceph/flex-migrator.yaml
Labels: skip-ci

#9280 helm: Use a more explicit value for ingress for K8s 1.18
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
Labels: backport-release-1.8

#9279 docs: sort common.yaml
  build/rbac/common.yaml.header
  deploy/examples/common.yaml
Labels: backport-release-1.8

#9282 mon: Set stretch tiebreaker reliably during failover
  pkg/daemon/ceph/client/mon.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: backport-release-1.7, backport-release-1.8

#9310 docs: sort common.yaml example (Backport #9279)
  build/rbac/common.yaml.header
  deploy/examples/common.yaml
Labels: backport

#9319 build: run mv outside the OLM_CATALOG_DIR
  deploy/olm/generate-rook-csv.sh
Labels: backport-release-1.8

#9315 rgw: add note that bucket notifications are experimental
  Documentation/ceph-object-bucket-notifications.md
Labels: docs, skip-ci, backport-release-1.8

#9312 Truncate job name of the osd prepare job further to avoid pod generation failure on K8s 1.22
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/k8sutil/k8sutil.go
  pkg/operator/k8sutil/k8sutil_test.go
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/ceph_settings.go
  tests/integration/ceph_helm_test.go
  tests/integration/ceph_smoke_test.go
Labels: backport-release-1.7, backport-release-1.8

#9332 build: updated locale for rbac generation
  build/rbac/keep-rbac-yaml.sh
Labels: backport-release-1.8

#9317 docs: revise upgrade doc for Rook v1.8
  Documentation/ceph-upgrade.md
Labels: backport-release-1.8

#9316 build: generate common.yaml from helm charts
  Makefile
  build/rbac/gen-common.sh
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/charts/library/templates/_cluster-serviceaccount.tpl
  deploy/charts/library/templates/_imagepullsecret.tpl
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.8

#9337 docs: Clarify helm chart version upgrades
  Documentation/ceph-upgrade.md
Labels: docs, skip-ci, backport-release-1.7, backport-release-1.8

#8452 mds: create EC pool as secondary pool
  Documentation/ceph-filesystem-crd.md
  deploy/examples/csi/cephfs/storageclass-ec.yaml
  deploy/examples/filesystem-ec.yaml
Labels: ceph, filesystem, backport-release-1.8

#9342 test: Upgrade test to update the toolbox spec
  tests/integration/ceph_upgrade_test.go
Labels: test, backport-release-1.8

#9214 pool: Update the desired failure domain when changed
  Documentation/ceph-advanced-configuration.md
  Documentation/ceph-pool-crd.md
  PendingReleaseNotes.md
  pkg/daemon/ceph/client/crush_rule.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
Labels: backport-release-1.8

#9281 docs: update NFS docs
  Documentation/ceph-nfs-crd.md
  Documentation/ceph-upgrade.md
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
Labels: backport-release-1.8

#9343 core: bump to ceph 16.2.7
  .github/workflows/rgw-multisite-test/action.yml
  Documentation/ceph-cluster-crd.md
  Documentation/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/olm/assemble/metadata-common.yaml
  design/ceph/ceph-cluster-cleanup.md
  images/ceph/Makefile
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.8

#9150 ceph: bucket notifications refactoring work
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/controller_test.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/object/notification/obc_label_controller_test.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/notification/s3ext.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/topic/controller_test.go
  pkg/operator/ceph/object/topic/provisioner.go
Labels: test, code cleanup, ceph-rgw

#9356 nfs: remove poolConfig
  Documentation/ceph-nfs-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/nfs/nfs.go
Labels: backport-release-1.8

#9362 nfs: make rados.namespace optional
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.8

#8776 ceph: removing fs_name arg from daemon status cmd
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/client/filesystem_mirror.go
  pkg/daemon/ceph/client/filesystem_mirror_test.go
Labels: ceph, backport-release-1.8

#9357 helm: rook-ceph chart: Set up webhook cert volume
  deploy/charts/rook-ceph/templates/deployment.yaml
Labels: backport-release-1.8

#9169 test: add more test cases for bucket notfication
  tests/framework/clients/bucket.go
  tests/framework/clients/notification.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_bucket_notification_test.go
Labels: backport-release-1.8

#9372 docs: add instructions to upgrade admission controller
  Documentation/ceph-upgrade.md
Labels: skip-ci, backport-release-1.8

#9380 osd: cleanup cluster using the root UID
  pkg/operator/ceph/cluster/cleanup.go
Labels: backport-release-1.8

#9397 core: add context to k8sutil replicaset and secret
  pkg/operator/ceph/controller/mirror_peer.go
  pkg/operator/k8sutil/replicaset.go
  pkg/operator/k8sutil/secret.go
Labels: backport-release-1.8

#9396 core: add context parameter to k8sutil service
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mon/service.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/webhook.go
  pkg/operator/k8sutil/service.go
Labels: backport-release-1.8

#9393 core: add context parameter to k8sutil endpoint
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/k8sutil/endpoint.go
Labels: backport-release-1.8

#9394 core: add context parameter to k8sutil configMap
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  pkg/operator/k8sutil/configmap.go
  pkg/operator/k8sutil/configmap_test.go
Labels: backport-release-1.8

#9392 core: add context parameter to k8sutil prometheus
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/k8sutil/prometheus.go
Labels: backport-release-1.8

#9391 core: add context parameter to k8sutil pvc
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/k8sutil/pvc.go
  pkg/operator/k8sutil/pvc_test.go
Labels: backport-release-1.8

#9395 core: add context parameter to k8sutil kvstore
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/osd/status.go
  pkg/operator/ceph/cluster/osd/status_test.go
  pkg/operator/ceph/object/mime.go
  pkg/operator/k8sutil/kvstore.go
  pkg/operator/k8sutil/kvstore_test.go
Labels: backport-release-1.8

#9410 security: use correct osd tags for restricted caps with external cluster script
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.8

#9417 pool: file: object: clean up health checkers for force deletion
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/pool/controller.go
Labels: backport-release-1.8

#9415 build: Add K8s 1.23 to the CI tests
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/setup-cluster-resources/action.yaml
Labels: build

#9276 pool: add rbd ec pool support in external cluster
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/pool-ec.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.8

#9423 build: updating tini init command in direct mount toolbox
  deploy/examples/direct-mount.yaml
Labels: skip-ci, backport-release-1.8

#9296 file: allow to create CephFS dataPools with predefined names
  Documentation/ceph-filesystem-crd.md
  Documentation/ceph-filesystem.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/csi/cephfs/storageclass-ec.yaml
  deploy/examples/csi/cephfs/storageclass.yaml
  deploy/examples/filesystem-ec.yaml
  deploy/examples/filesystem-test.yaml
  deploy/examples/filesystem.yaml
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
Labels: feature, filesystem, backport-release-1.8

#9388 helm: add optional monitoring RBAC to operator chart
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  deploy/charts/library/templates/_cluster-monitoring.tpl
  deploy/charts/rook-ceph/templates/cluster-rbac.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.8

#9416 pool: file: object: clean up health checkers for both types of deletion (backport #9094)
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/pool/controller.go
Labels: backport

#9386 mgr: run the watch side car config on /etc/ceph
  cmd/rook/ceph/mgr.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.8

#9363 pool: Allow configuration of built-in pools with non-k8s names
  .github/workflows/canary-integration-test.yml
  Documentation/ceph-pool-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/crds.yaml
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
  deploy/examples/pool-device-health-metrics.yaml
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/pool_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/crush_rule_test.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/mirror_test.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/predicate_test.go
  pkg/operator/ceph/csi/peermap/config_test.go
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/health.go
  pkg/operator/ceph/pool/validate.go
  pkg/operator/ceph/pool/validate_test.go
  tests/framework/clients/nfs.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_base_file_test.go
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.8

#9418 mds: Skip sanity check during upgrades to 16.2.7
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
Labels: backport-release-1.8

#9439 osd: add CAP_MKNOD to PSP
  build/rbac/rbac.yaml
  deploy/charts/rook-ceph/templates/psp.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.8

#9189 security: add dry run mode for external cluster script
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.8

#9453 docs: add jumbo frames note to common issues
  Documentation/ceph-common-issues.md
Labels: backport-release-1.7, backport-release-1.8

#9441 ceph: fix blockOwnerDeletion error
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.8

#9465 docs: Recommend primary affinity over hybrid pools
  Documentation/ceph-pool-crd.md
Labels: skip-ci, backport-release-1.8

#9464 osd: Add label to osd purge job
  deploy/examples/osd-purge.yaml
Labels: skip-ci

#9473 docs: fixed typo on rbd mirroring documentation
  Documentation/rbd-mirroring.md
Labels: skip-ci

#9457 core: disallow multiple clusters in the same namespace
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/predicate.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/controller/predicate_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/disruption/clusterdisruption/add.go
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/bucket/predicate.go
Labels: backport-release-1.8

#9434 osd: handle removal of encrypted osd deployment
  .github/workflows/canary-integration-test.yml
  pkg/clusterd/disk.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/util/sys/device.go
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.8

#9365 object: fix handling for notifications for OBC
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/controller_test.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/object/notification/obc_label_controller_test.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/notification/s3ext.go
Labels: backport-release-1.8

#9384 subvolumegroup: add new crd
  .commitlintrc.json
  .github/workflows/canary-integration-test.yml
  Documentation/ceph-fs-subvolumegroup.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/subvolumegroup.yaml
  deploy/olm/assemble/metadata-common.yaml
  pkg/apis/ceph.rook.io/v1/filesystem.go
  pkg/apis/ceph.rook.io/v1/register.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephfilesystemsubvolumegroup.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_cephfilesystemsubvolumegroup.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/generated_expansion.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/cephfilesystemsubvolumegroup.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/ceph.rook.io/v1/cephfilesystemsubvolumegroup.go
  pkg/client/listers/ceph.rook.io/v1/expansion_generated.go
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/operator/ceph/cluster/dependents.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/dependent.go
  pkg/operator/ceph/file/dependent_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.8

#9489 build: add missing helm
  INSTALL.md
Labels: skip-ci, backport-release-1.8

#9491 Update ceph-monitoring.md
  Documentation/ceph-monitoring.md
Labels: skip-ci
