Repository rook/rook, pull requests merged in 2022-11, with the labels that each got.

#11213 docs: added steps to collect coredump and perf troubleshooting info
  Documentation/Troubleshooting/performance-profiling.md
Labels: skip-ci, backport-release-1.10

#11255 docs: Update roadmap for the v1.11 release
  ROADMAP.md
Labels: skip-ci

#11256 docs: update disaster recovery guide for webhook
  Documentation/Troubleshooting/disaster-recovery.md
Labels: docs, skip-ci, backport-release-1.9, backport-release-1.10

#11159 osd: add deviceType label to an OSD
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/osd.go
Labels: backport-release-1.10

#11233 core: validate crd name size from admission controller
  pkg/apis/ceph.rook.io/v1/object.go
Labels: backport-release-1.10

#11269 fix: bugs following docs for NixOS deployment
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.10

#11202 object: do not create service for external object stores
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/controller_test.go
  pkg/operator/ceph/object/notification/obc_label_controller_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
  pkg/operator/ceph/object/status.go
  tests/integration/ceph_object_test.go
Labels: backport-release-1.10

#11280 core: include userID/userKey to secret generated from CephClient
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
Labels: backport-release-1.10

#10887 mon: Remove out of quorum mons from ceph.conf
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/client/info.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/controller/cluster_info.go
Labels: backport-release-1.10

#11278 core: Add ability to add resources on discovery DaemonSet
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/util.go
  pkg/operator/discover/discover.go
  pkg/operator/k8sutil/resources.go
  pkg/operator/k8sutil/resources_test.go
Labels: backport-release-1.10

#11289 docs: Set CRD page titles to the CRD name
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
  Documentation/CRDs/Block-Storage/ceph-rbd-mirror-crd.md
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Object-Storage/.pages
  Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-zone-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-zonegroup-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-fs-mirror-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/ceph-client-crd.md
  Documentation/CRDs/ceph-nfs-crd.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
Labels: skip-ci, backport-release-1.10

#10652 docs: add additional RBD image features to docs and YAML files
  Documentation/CRDs/Cluster/external-cluster.md
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/csi/rbd/storageclass-ec.yaml
  deploy/examples/csi/rbd/storageclass.yaml
  deploy/examples/import-external-cluster.sh
  design/ceph/ceph-config-updates.md
Labels: backport-release-1.10

#11303 helm: set DISCOVER_DAEMON_UDEV_BLACKLIST
  deploy/charts/rook-ceph/templates/deployment.yaml
Labels: backport-release-1.10

#11290 docs: Clarify in docs and readme that Rook focuses on Ceph
  Documentation/Contributing/.pages
  Documentation/Contributing/storage-providers.md
  Documentation/README.md
  README.md
Labels: skip-ci

#11315 docs: Clarify csi already exists error in docs
  Documentation/Troubleshooting/ceph-csi-common-issues.md
Labels: skip-ci, backport-release-1.10

#11324 docs: update rbd-mirror doc
  Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md
Labels: docs, skip-ci, backport-release-1.10

#11322 crash: Fix a bug where crash collectors in wrong namespaces were deleted
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: backport-release-1.10

#11342 object: update to latest obc controller to fix ob status
  go.mod
  go.sum
Labels: object bucket claims (OBC), backport-release-1.10

#11334 csi: add a parameter to modify the maxUnavailable value of rbd daemonset.
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: backport-release-1.10

#11362 doc: fix wrong format caused by merge conflict
  Documentation/Helm-Charts/operator-chart.md
Labels: backport, skip-ci

#11361 osd: improve log on specifying lv and loop device as osd
  pkg/daemon/ceph/osd/daemon.go
Labels: backport-release-1.10
