Repository rook/rook, pull requests merged in 2022-06, with the labels that each got.

#10345 docs: add prepareosd to placement
  Documentation/CRDs/ceph-cluster-crd.md
  deploy/examples/cluster.yaml
Labels: skip-ci, backport-release-1.9

#10362 pool: Delete ceph pool when blockpool cr is deleted
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/pool_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/validate.go
Labels: backport-release-1.9

#10309 rgw: make fqdn rgw converted to ip everywhere
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.9

#10382 build: Flannel flag to minikube is causing test failures
  .github/workflows/setup-cluster-resources/action.yaml
Labels: backport-release-1.9

#10383 osd: ignore the region label when it is the same as zone label in topology
  pkg/operator/ceph/cluster/osd/topology.go
  pkg/operator/ceph/cluster/osd/topology_test.go
Labels: backport-release-1.9

#10380 csi: do not block the reconcile if all clusters are not ready
  pkg/operator/ceph/csi/controller.go
Labels: backport-release-1.9

#10373 osd: do not hide the error
  pkg/daemon/ceph/osd/kms/kms_test.go
  pkg/daemon/ceph/osd/kms/vault.go
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.9

#10306 csi: update sidecar to latest release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/general_manifests.go
Labels: csi

#10399 external: format python files using tool black
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.9

#10342 ceph: Add holder pod if csi host networking is disabled
  .github/workflows/canary-integration-test.yml
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/spec_test.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  tests/scripts/github-action-helper.sh
  tests/scripts/validate_cluster.sh
Labels: ceph, csi, backport-release-1.9

#10341 core: Report basic cluster and version telemetry
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/telemetry/telemetry.go
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.9

#10333 test: Fix encrypted OSDs on latest Ceph releases and add canary test for encrypted osd in host-based cluster
  .github/workflows/canary-integration-test.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  pkg/operator/ceph/cluster/osd/spec.go
  tests/scripts/github-action-helper.sh
Labels: test, ceph-osd, backport-release-1.9

#10424 csi: update cephcsi from 3.6.1 to 3.6.2
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: csi, backport-release-1.9

#10405 mon: update node labels as per new key value
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
Labels: backport-release-1.9

#10448 docs: Remove obsolete limitation from multus docs
  Documentation/CRDs/ceph-cluster-crd.md
Labels: skip-ci, backport-release-1.9

#10234 doc: update ceph external cluster flags
  Documentation/CRDs/ceph-cluster-crd.md
Labels: skip-ci

#10445 osd: add lvm flag for lvm osd activate
  pkg/daemon/ceph/osd/daemon.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.9

#10454 ceph: update CSI-Addons side-car to latest (v0.4.0) release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.9

#10460 core: increase liveness probe timeout to 2s
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: backport-release-1.9

#9915 file: block deletion on more dependents
  pkg/daemon/ceph/client/filesystem.go
  pkg/daemon/ceph/client/filesystem_test.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/controller_test.go
  pkg/operator/ceph/file/dependent.go
  pkg/operator/ceph/file/dependent_test.go
  pkg/operator/ceph/file/filesystem.go
  tests/framework/clients/filesystem.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_base_file_test.go
Labels: filesystem, backport-release-1.9

#10478 doc: update k8s-csi-addons controller links to v0.4.0
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
Labels: docs, skip-ci, backport-release-1.9

#10496 osd: increase memory of osd prepare pods
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.9

#10480 core: delete v1beta1 cronjob only when v1 not found
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: backport-release-1.9

#10490 csi: fix stagingpath
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: backport-release-1.9

#10505 mon: Disable insecure global ids for new deployments
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/config/config.go
  pkg/operator/ceph/config/config_test.go
Labels: backport-release-1.9

#10514 build: add separate docs build and preview targets
  .github/workflows/docs-check.yml
  Makefile
  build/release/Makefile
  build/release/requirements_docs.txt
  mkdocs.yml
Labels: docs, ci

#10520 build: fix working dir for docs building
  build/release/Makefile
Labels: build, docs

#10154 helm: use correct namespace for provisioner in cephobjectstore template
  Documentation/Upgrade/rook-upgrade.md
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.9

#10459 external: add support for subvolumegroup and rados namespace
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.9

#10537 ci: skip daily nightly job on fork
  .github/workflows/daily-nightly-jobs.yml
Labels: ci
