Repository rook/rook, pull requests merged in 2022-10, with the labels that each got.

#11029 docs: explain specific nixos configurations
  Documentation/Getting-Started/Prerequisites/prerequisites.md
Labels: docs, skip-ci, backport-release-1.10

#11101 docs: fix notes in docs
  Documentation/Contributing/development-environment.md
Labels: skip-ci, backport-release-1.10

#11104 mgr: Set the public dashboard port differently from the target port
  pkg/operator/ceph/cluster/mgr/config.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/dashboard_test.go
  pkg/operator/ceph/cluster/mgr/spec.go
Labels: backport-release-1.9, backport-release-1.10

#11110 nfs: fix nfs grace period when multus is enabled
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/command_test.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  tests/scripts/github-action-helper.sh
Labels: bug, ceph-nfs, backport-release-1.10

#11131 ci: update mon_data_avail_warn percentage
  deploy/examples/cluster-test.yaml
Labels: backport-release-1.9, backport-release-1.10

#10877 tests: improved filesystem snapshot mirroring integration tests
  .github/workflows/canary-integration-test.yml
Labels: ceph, filesystem, test

#11136 docs: Document expectations for releases
  Documentation/Getting-Started/.pages
  Documentation/Getting-Started/release-cycle.md
Labels: skip-ci, backport-release-1.10

#11122 docs: add point about physical disks visualization in dashboard
  Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md
Labels: docs, skip-ci

#11099 operator: Don't remove existing pools for mgr/prometheus/rbd_stats_pools
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: backport-release-1.10

#10986 core: increase liveness probe timeout to 5s
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.10

#11138 osd: osdSafeToDestroy check should be after osd out
  pkg/daemon/ceph/osd/remove.go
Labels: backport-release-1.10

#11165 csi: add setmetadata and clustername flag to omap
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: csi

#11090 external: fix endpoint_dial check for rgw endpoint
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.10

#11158 csi: Add nfs snap & clone ci
  tests/framework/clients/nfs.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_base_file_test.go
  tests/integration/ceph_base_nfs_test.go
Labels: csi

#11163 core: enabling logCollector by default for coredump collection
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster.yaml
  tests/framework/installer/ceph_manifests.go
Labels: troubleshooting, backport-release-1.10

#11182 operator: Remove obsolete flex driver properties
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
Labels: backport-release-1.10

#11178 csi: update csi to latest release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#11171 docs: updated syntax in markdown files
  Documentation/Contributing/development-flow.md
  INSTALL.md
  design/ceph/ceph-config-updates.md
  design/ceph/interacting-with-rook-resources.md
Labels: backport-release-1.10

#11197 docs: adding enableRBDStats example in helm chart deployment
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: docs

#11154 Docs: Improve troubleshooting docs on restoring CRDs after deletion
  Documentation/Troubleshooting/disaster-recovery.md
Labels: skip-ci, backport-release-1.10

#11124 object: remove health checker
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/object-ec.yaml
  deploy/examples/object-openshift.yaml
  deploy/examples/object.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/dependents.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/status.go
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_base_object_test.go
Labels: objectstore, ceph-rgw

#11203 docs: fix typo in numbering
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
Labels: skip-ci, backport-release-1.10

#11198 core: upgrade ceph to latest release v17.2.5
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/external-cluster.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/examples/toolbox.yaml
  deploy/olm/assemble/metadata-common.yaml
  design/ceph/ceph-cluster-cleanup.md
  design/ceph/ceph-nfs-ganesha.md
  images/ceph/Makefile
  pkg/operator/ceph/nfs/security_test.go
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.10

#11179 core: Retry when removing finalizers from cluster resources
  pkg/operator/ceph/cluster/controller.go
Labels: backport-release-1.10

#11211 mon: The mon daemons maintain host network settings to allow change in config
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  pkg/apis/ceph.rook.io/v1/cluster.go
  pkg/apis/ceph.rook.io/v1/cluster_test.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/mon/spec.go
Labels: backport-release-1.10

#11223 security: update "s5cmd" to "v2.0.0"
  images/ceph/Makefile
Labels: backport-release-1.9, backport-release-1.10

#11219 security: Run the crash collector as ceph user
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.9, backport-release-1.10
