Repository rook/rook, pull requests merged in 2022-03, with the labels that each got.

#9567 csi: add custom ceph.conf for csi pods
  Documentation/ceph-advanced-configuration.md
  PendingReleaseNotes.md
  deploy/examples/csi-ceph-conf-override.yaml
  pkg/operator/ceph/csi/ceph_config.go
  pkg/operator/ceph/csi/ceph_config_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  tests/framework/installer/ceph_installer.go
Labels: csi

#9816 docs: correct ceph toolbox path
  Documentation/ceph-common-issues.md
Labels: backport-release-1.8

#9821 operator: Document that the `rook-ceph-operator-config` ConfigMap is …
  Documentation/ceph-common-issues.md
  Documentation/ceph-upgrade.md
Labels: backport-release-1.8

#9829 Documentation/ceph-teardown.md: fix typo
  Documentation/ceph-teardown.md
Labels: skip-ci, backport-release-1.8

#9834 core: Disruption controller log ceph errors in debug level
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: backport-release-1.8

#9838 helm: add cephFileSystems storageClass.pool
  Documentation/helm-ceph-cluster.md
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.8

#9842 osd: disable raw mode for specific disk configs
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: bug, ceph-osd, backport-release-1.8

#9841 helm: Remove obsolete setting for enabling multiple filesystems
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.8

#9859 nfs: remove secret, configmap when downscaling CephNFS
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/nfs/spec.go
Labels: bug, ceph-nfs, backport-release-1.8

#9863 helm: .Values.image.prefix is not referenced anywhere
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.8

#9847 core: sync ceph fsid on cephcluster status
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/cephstatus.go
Labels: backport-release-1.8

#9868 core: fix empty string bug
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/csi/util_test.go
Labels: backport-release-1.8

#9884 osd: clarify vault auth error message
  pkg/daemon/ceph/osd/kms/vault_api.go
Labels: backport-release-1.8

#9888 mon: Disable startup probe on canary pods
  pkg/operator/ceph/cluster/mon/mon.go
Labels: backport-release-1.8

#9878 csi: Populate mon endpoints even if driver not enabled
  pkg/operator/ceph/csi/cluster_config.go
Labels: backport-release-1.8

#9873 core: rework usage of ReportReconcileResult
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/reporting_test.go
Labels: backport-release-1.8

#9862 core: fix incorrect join command
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.8

#9879 ci: add pylint in ci
  .github/workflows/linters.yaml
Labels: ci

#9908 file: add events to filesystem reconcile
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/controller_test.go
Labels: filesystem

#9930 test: avoid potential data inconsistency on zapping disk
  tests/scripts/github-action-helper.sh
  tests/scripts/multi-node/build-rook.sh
Labels: test, backport-release-1.8

#9910 core: add `Phase` in `additionalPrinterColumns` for all CRs
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.8

#9906 object: remove region option from OBC StorageClass
  Documentation/ceph-examples.md
  Documentation/ceph-object-bucket-claim.md
  Documentation/ceph-object.md
  PendingReleaseNotes.md
  deploy/examples/storageclass-bucket-delete.yaml
  deploy/examples/storageclass-bucket-retain.yaml
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/health.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/s3-handlers_test.go
  pkg/operator/ceph/object/topic/provisioner.go
  tests/framework/clients/bucket.go
  tests/framework/installer/ceph_helm_installer.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_base_object_test.go
  tests/integration/ceph_bucket_notification_test.go
  tests/integration/ceph_object_test.go
  tests/integration/ceph_upgrade_test.go
Labels: objectstore, object bucket claims (OBC), backport-release-1.8

#9898 core: fix GetLogCollectorResources to get the right resources
  pkg/apis/ceph.rook.io/v1/resources.go
Labels: backport-release-1.8

#9956 ci: fixed pylint failure
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.8

#9941 csi: mount serviceaccount oidc-token into csi-driver
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: csi
