Repository rook/rook, pull requests merged in 2022-04, with the labels that each got.

#9969 build: Add mergify rules for release-1.9
  .mergify.yml
Labels: skip-ci

#9967 osd: add NixOS specific PATHs
  pkg/daemon/ceph/osd/nsenter.go
Labels: backport-release-1.8, backport-release-1.9

#9964 object: add service account for RGW pod
  Documentation/authenticated-registry.md
  PendingReleaseNotes.md
  deploy/charts/library/templates/_cluster-serviceaccount.tpl
  deploy/examples/common-second-cluster.yaml
  deploy/examples/common.yaml
  deploy/examples/operator-openshift.yaml
  pkg/apis/ceph.rook.io/v1/scc.go
  pkg/operator/ceph/object/spec.go
  tests/framework/installer/ceph_settings.go
Labels: backport-release-1.9

#9968 docs: update the s3 client example for accesing RGW
  Documentation/ceph-object.md
Labels: docs, skip-ci, backport-release-1.8, backport-release-1.9

#9952 csi: make use of create-external-cluster-resources.py upstream
  Documentation/ceph-cluster-crd.md
  deploy/examples/common-external.yaml
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/create-external-cluster-resources.sh
Labels: backport-release-1.9

#9974 object: add details about route for rgw's https endpoint
  deploy/examples/object-openshift.yaml
Labels: backport-release-1.9

#10002 csi: update cephcsi to v3.6.0 release
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
Labels: backport-release-1.9

#9997 Upgrade docs for 1.9
  Documentation/ceph-monitoring.md
  Documentation/ceph-pool-crd.md
  Documentation/ceph-upgrade.md
  PendingReleaseNotes.md
  deploy/examples/cluster-test.yaml
  deploy/examples/pool-builtin-mgr.yaml
  design/common/object-bucket.md
Labels: skip-ci, backport-release-1.9

#10010 docs: fix design doc link
  Documentation/development-flow.md
Labels: skip-ci, backport-release-1.8, backport-release-1.9

#9919 build: Remove obsolete cross build container
  .github/workflows/shellcheck.yaml
  INSTALL.md
  Makefile
  PendingReleaseNotes.md
  build/common.sh
  build/makelib/common.mk
  build/reset
  build/run
  images/Makefile
  images/cross/Dockerfile
  images/cross/Makefile
  images/cross/rsyncd.sh
  images/cross/run.sh
Labels: backport-release-1.9

#10016 docs: Remove obsolete section of upgrade guide
  Documentation/ceph-upgrade.md
Labels: skip-ci, backport-release-1.9

#10018 docs: Add missing references to branch name script
  Documentation/ceph-advanced-configuration.md
  Documentation/ceph-csi-snapshot.md
  Documentation/ceph-csi-volume-clone.md
  Documentation/ceph-pool-crd.md
Labels: skip-ci, backport-release-1.8, backport-release-1.9

#10029 test: Default pool replica size for test cluster is 1
  deploy/examples/cluster-test.yaml
Labels: backport-release-1.9

#9934 core: start admission controller without any script
  Documentation/admission-controller-usage.md
  Documentation/pre-reqs.md
  build/rbac/rbac.yaml
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/operator.yaml
  go.mod
  go.sum
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/webhook-config.go
  pkg/operator/ceph/webhook.go
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/ceph_settings.go
  tests/integration/ceph_helm_test.go
  tests/scripts/deploy_admission_controller_test.sh
  tests/scripts/deploy_cert_manager.sh
  tests/scripts/webhook-config.yaml
Labels: backport-release-1.9

#10009 csi: remove node object update rbac for csi deamonset pods
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.9

#10028 monitoring: Only set prometheus rules ownerref in same namespace
  pkg/operator/ceph/cluster/mgr/mgr.go
Labels: backport

#10027 helm: Correctly check external cluster for prometheus rules
  deploy/charts/rook-ceph-cluster/templates/prometheusrules.yaml
Labels: backport-release-1.9

#10044 docs: update design doc path in multus design
  design/ceph/multus-network.md
Labels: docs, skip-ci

#10048 ci: add multus integration test
  .github/workflows/canary-integration-test.yml
  .github/workflows/setup-cluster-resources/action.yaml
  deploy/examples/cluster-multus-test.yaml
  tests/scripts/github-action-helper.sh
  tests/scripts/validate_cluster.sh
Labels: backport-release-1.9

#10003 core: support arbitrary node affinity inputs
  deploy/examples/operator.yaml
  go.mod
  pkg/operator/k8sutil/node.go
  pkg/operator/k8sutil/node_test.go
Labels: backport-release-1.9

#9927 csi: add nfs nodeplugin & provisioner
  Documentation/helm-operator.md
  build/rbac/get-helm-rbac.sh
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/serviceaccount.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/csi/nfs/pod.yaml
  deploy/examples/csi/nfs/pvc.yaml
  deploy/examples/csi/nfs/storageclass.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  images/ceph/Makefile
  pkg/operator/ceph/csi/betav1csidriver.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/csidriver.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
Labels: csi, ceph-nfs, backport-release-1.9

#10053 pool: built-in pools must be replicated
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/operator/ceph/pool/validate.go
  pkg/operator/ceph/pool/validate_test.go
Labels: block, backport-release-1.9

#10054 nfs: create config pool automatically
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
Labels: backport-release-1.9

#10062 build: Remove requirement for ibm test in backports
  .mergify.yml
Labels: skip-ci

#10066 docs: Clarify helm install documentation
  Documentation/helm-ceph-cluster.md
  Documentation/helm-operator.md
Labels: skip-ci, backport-release-1.9

#10014 docs: update NFS docs including latest CSI work
  Documentation/ceph-csi-drivers.md
  Documentation/ceph-nfs-crd.md
  Documentation/ceph-upgrade.md
  deploy/examples/nfs-load-balancer.yaml
  deploy/examples/nfs-test.yaml
  deploy/examples/nfs.yaml
Labels: docs, ceph-nfs, backport-release-1.9

#10076 docs: fix nfs permission on openshift example
  deploy/examples/operator-openshift.yaml
Labels: skip-ci, backport-release-1.9

#10078 docs: add info about mounting NFS exports externally
  Documentation/ceph-nfs-crd.md
Labels: docs, skip-ci, backport-release-1.9

#10071 csi: enable csi nfs to generate nfs rbac for csv
  deploy/olm/generate-rook-csv.sh
Labels: csi, ceph-nfs, backport-release-1.9

#10088 osd: Enable quincy osd release version
  pkg/operator/ceph/cluster/osd/osd.go
Labels: backport-release-1.9

#10093 helm: add ingressClassName field
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.8, backport-release-1.9

#10099 block: validate updating names in BlockPool CR
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/pool_test.go
Labels: bug, ceph, backport-release-1.9

#10094 build: update golang version to v1.17
  .github/workflows/build.yml
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-setup/action.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/setup-cluster-resources/action.yaml
  .github/workflows/unit-test.yml
  build/makelib/golang.mk
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
Labels: backport-release-1.9

#9940 csi: add CSI encryption support
  Documentation/ceph-csi-drivers.md
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/csi/rbd/storageclass.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: csi, backport-release-1.9

#10089 helm: fix missing default resources in rook components
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
Labels: backport-release-1.9

#10109 monitoring: Disable new alerts that are not applicable to rook
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/examples/monitoring/localrules.yaml
Labels: backport-release-1.9

#10096 core: Examples set default priority class names
  Documentation/ceph-cluster-crd.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/filesystem.yaml
  deploy/examples/object.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  tests/framework/installer/ceph_helm_installer.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_settings.go
  tests/framework/utils/k8s_helper.go
  tests/integration/ceph_base_deploy_test.go
Labels: backport-release-1.9

#10059 csi: use k8s.gcr.io for csi nfsplugin image
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  images/ceph/Makefile
  pkg/operator/ceph/csi/spec.go
Labels: csi, backport-release-1.9

#10111 subvolumegroup: refractor subvolumegroup controller
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
Labels: code cleanup

#10108 build: Add a placeholder rgw role for csv generation
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/charts/library/templates/_cluster-rolebinding.tpl
  deploy/examples/common.yaml
Labels: backport-release-1.9

#10023 core: update controller-runtime version to v0.11.2
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/operator/ceph/config/probes.go
  pkg/operator/ceph/config/probes_test.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
Labels: build, backport-release-1.9

#10118 test: Improve reliability of mon failover test
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_smoke_test.go
Labels: backport-release-1.9

#10127 build: add support for go 1.18
  .github/workflows/build.yml
  build/makelib/golang.mk
Labels: backport-release-1.9

#10124 csi: move setting csi param to setParams
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
Labels: csi, code cleanup, backport-release-1.9

#10142 build: Add a placeholder rule to the RGW RBAC
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/examples/common.yaml
Labels: backport-release-1.9

#10132 helm: ingressClassName should be available for networking.k8s.io/v1
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
Labels: backport-release-1.9

#10150 csi: update cephcsi to v3.6.1 release
  Documentation/ceph-upgrade.md
  Documentation/helm-operator.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.9

#10147 core: remove double imported packages
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/crash/crash_test.go
  pkg/operator/ceph/cluster/mgr/spec_test.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/osd/integration_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/controller/version.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/validate.go
  pkg/operator/test/client.go
  tests/integration/ceph_base_file_test.go
Labels: code cleanup, code enhancement

#10123 build: Update min version to k8s 1.17
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/ceph-block.md
  Documentation/ceph-cluster-crd.md
  Documentation/development-flow.md
  Documentation/helm-ceph-cluster.md
  Documentation/helm-operator.md
  Documentation/quickstart.md
  deploy/charts/rook-ceph-cluster/templates/_helpers.tpl
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/create_test.go
  tests/framework/installer/ceph_helm_installer.go
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/ceph_settings.go
  tests/integration/ceph_multi_cluster_test.go
  tests/scripts/deploy_cert_manager.sh
Labels: backport-release-1.9

#10125 build: update go-ceph version and remove ceph_preview
  .github/workflows/golangci-lint.yaml
  Makefile
  go.mod
  go.sum
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
Labels: backport-release-1.9

#9925 core: fix csi-cephfsplugin pod restart on non-hostnetworking env
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/cleanup/hostpath.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/config.go
  pkg/operator/ceph/cluster/mon/env.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/mon/node.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/mon/predicate.go
  pkg/operator/ceph/cluster/rbd/controller.go
  pkg/operator/ceph/cluster/version.go
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/spec_test.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/mirror/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/realm/controller.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zonegroup/controller.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/k8sutil/daemonset.go
  tests/scripts/collect-logs.sh
  tests/scripts/github-action-helper.sh
  tests/scripts/validate_cluster.sh
Labels: backport-release-1.9

#10173 ci: wait for cert while deploying vault
  tests/scripts/generate-tls-config.sh
Labels: backport-release-1.9

#10137 rgw: fix dashboard admin creation for multiple object stores
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/user.go
  tests/integration/ceph_base_object_test.go
  tests/integration/ceph_helm_test.go
  tests/integration/ceph_object_test.go
  tests/integration/ceph_smoke_test.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.9

#9936 helm: add ingress annotations for ssl
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.9
