Repository rook/rook, pull requests merged in 2022-12, with the labels that each got.

#11338 osd: re-open encrypted disk during osd-prepare-job if closed
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/config_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
  pkg/util/exec/translate_exec.go
Labels: ceph-osd, backport-release-1.10

#11360 docs: add ceph-exporter design doc
  design/ceph/ceph-exporter.md
Labels: design, skip-ci

#11387 osd: remove stale dm device during osd-prepare-job
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/volume.go
Labels: bug, ceph-osd, backport-release-1.10

#11403 docs: Fix notes in CephBucketTopic docs
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
Labels: skip-ci, backport-release-1.10

#11399 core: Allow ceph.conf to be updated if already exists
  pkg/daemon/ceph/client/config.go
  pkg/daemon/ceph/osd/remove.go
Labels: backport-release-1.10

#11414 osd: Replace dot with dash in storageClassDeviceSet names since used as volume names
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: backport-release-1.10

#11439 ci: upgrade minikube action to latest version
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
Labels: backport-release-1.10

#11405 docs: import external K8s cluster on existing cluster
  Documentation/CRDs/Cluster/external-cluster.md
Labels: skip-ci

#11432 operator: disable webhook by default
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/webhook-config.go
  pkg/operator/ceph/webhook.go
Labels: backport-release-1.10

#11301 OSD prepare job cannot create vols with /dev/mapper alias on PVCs
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: backport-release-1.10

#11434 core: Read mon secret from file instead of env var
  cmd/rook/ceph/ceph.go
  cmd/rook/ceph/mgr.go
  cmd/rook/ceph/osd.go
  cmd/rook/ceph/osd_test.go
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox.yaml
  images/ceph/toolbox.sh
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/config.go
  pkg/operator/ceph/cluster/mon/env.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
Labels: backport-release-1.10

#11448 operator: adding logs for debugging
  pkg/operator/ceph/webhook-config.go
Labels: backport-release-1.10

#11427 build: move to Go 1.19 as default version for building services
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/mod-check.yml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/unit-test.yml
Labels: backport-release-1.10

#11456 docs: Add link to failover and failback topic
  Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md
Labels: skip-ci, backport-release-1.10

#11377 helm: allow to specify allowed topologies for storage class
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.10

#11467 doc: update csi registry in custom-images
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
Labels: docs, skip-ci, backport-release-1.10

#11468 csi: add missing update rbac
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  deploy/examples/csi/nfs/rbac.yaml
Labels: csi, backport-release-1.10
