Repository rook/rook, pull requests merged in 2022-09, with the labels that each got.

#10381 doc: add documentation for sharing a CephFS PVC across namespaces
  Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md
Labels: skip-ci, backport-release-1.10

#10781 docs/storage-config: add yaml way of configuring pg_num and pgp_num
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  Documentation/Storage-Configuration/Advanced/configuration.md
Labels: skip-ci, backport-release-1.10

#10855 osd: disallow to create osd on lv with metadata device
  pkg/daemon/ceph/osd/daemon.go
Labels: backport-release-1.9, backport-release-1.10

#10861 docs: add missed sssdConfigFile params for NFS CRD
  Documentation/CRDs/ceph-nfs-crd.md
Labels: docs, skip-ci, backport-release-1.10

#10856 ci: remove older k8s config since we moved to 1.19
  .github/workflows/integration-test-config-older-k8s/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
Labels: backport-release-1.10

#10874 ci: fix release tests configuration
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
Labels: ci, backport-release-1.10

#10875 csi: fix holder pod creation in openshift multus cluster
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
Labels: backport-release-1.9, backport-release-1.10

#10882 test: Wait for resource deletion during helm uninstall
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.9, backport-release-1.10

#10858 osd: refactor code
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.9, backport-release-1.10

#10854 csi: change the default fsgroup policy for CSI driver object
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#10893 ci: no need to copy working dir to GOPATH
  .github/workflows/build.yml
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/rbac-gen.yaml
  .github/workflows/unit-test.yml
Labels: ci, backport-release-1.10

#10732 docs: add kerberos to nfs-ganesha design
  design/ceph/ceph-nfs-ganesha.md
Labels: skip-ci

#10791 csi: use cephcsi image for nfs nodeserver + holder design
  .github/workflows/canary-integration-test.yml
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  tests/scripts/github-action-helper.sh
  tests/scripts/validate_cluster.sh
Labels: csi, ceph-nfs, backport-release-1.10

#10903 bot: Fix automerge for 1.10 backports
  .mergify.yml
Labels: skip-ci

#10899 manifest: fix unexpected end of stream
  build/crds/build-crds.sh
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
Labels: backport-release-1.10

#10777 rbd-mirror: remove volume replication sidecar
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Block-Storage-RBD/rbd-mirroring.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  build/crds/build-crds.sh
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.10

#10904 helm: set OBC storageclass name to right namespace
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
Labels: backport-release-1.9, backport-release-1.10

#10906 csi: remove findCSIChange from predicate
  pkg/operator/ceph/csi/predicate.go
  pkg/operator/ceph/csi/predicate_test.go
Labels: csi, backport-release-1.9, backport-release-1.10

#10776 operator: improve ProbeHandler error message
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: backport-release-1.9, backport-release-1.10

#10937 helm: Warn to upgrade to 1.9.10 before k8s 1.25
  Documentation/Upgrade/rook-upgrade.md
Labels: skip-ci, backport-release-1.10

#10892 csi: add support for NFS snap, restore clone & resize
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/csi/nfs/pvc-clone.yaml
  deploy/examples/csi/nfs/pvc-restore.yaml
  deploy/examples/csi/nfs/rbac.yaml
  deploy/examples/csi/nfs/snapshot.yaml
  deploy/examples/csi/nfs/snapshotclass.yaml
  deploy/examples/csi/nfs/storageclass.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
Labels: csi, ceph-nfs, backport-release-1.10

#10951 docs: Clarify storage prereqs in quickstart guide
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
Labels: skip-ci, backport-release-1.10

#10943 csi: add topology provisioning support
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: csi, backport-release-1.10

#10728 rgw: delete zone/pools for multisite configuation
  Documentation/CRDs/Object-Storage/ceph-object-multisite-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/object-multisite-test.yaml
  deploy/examples/object-multisite.yaml
  design/ceph/object/ceph-multisite-overview.md
  design/ceph/object/zone.md
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/dependents.go
  pkg/operator/ceph/object/dependents_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/dependents.go
  pkg/operator/ceph/object/zone/dependents_test.go
Labels: objectstore, backport-release-1.10

#10931 external: do not add info=read cap if ceph version doesn't support it
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.9, backport-release-1.10

#10963 pool: initialize only rbd application pools
  pkg/operator/ceph/pool/controller.go
Labels: block, backport-release-1.10

#10950 nfs: add kerberos client security support
  Documentation/CRDs/ceph-nfs-crd.md
  Documentation/Storage-Configuration/NFS/nfs-security.md
  Documentation/Storage-Configuration/NFS/nfs.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/nfs.yaml
  design/ceph/ceph-nfs-ganesha.md
  pkg/apis/ceph.rook.io/v1/nfs.go
  pkg/apis/ceph.rook.io/v1/nfs_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/command.go
  pkg/daemon/ceph/client/rados.go
  pkg/daemon/ceph/client/rados_test.go
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/nfs/nfs.go
  pkg/operator/ceph/nfs/security.go
  pkg/operator/ceph/nfs/security_test.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/nfs/spec_test.go
  pkg/util/exec/exec.go
  pkg/util/exec/exec_test.go
  pkg/util/exec/test/mockexec.go
Labels: security, ceph-nfs, backport-release-1.10

#10965 build: update goceph module to v0.17
  go.mod
  go.sum
Labels: backport-release-1.10

#10700 monitoring: fix pool growth warning grouping
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/examples/monitoring/localrules.yaml
Labels: backport-release-1.9, backport-release-1.10

#10969 ci: disallow to create encrypted osd on lv and osd on lv with metadata device
  pkg/daemon/ceph/osd/daemon.go
Labels: backport-release-1.9, backport-release-1.10

#10975 build: Stop printing verbose rbac generation details
  build/rbac/keep-rbac-yaml.sh
Labels: backport-release-1.10

#10968 osd: disallow to create encrypted osd on partition
  pkg/daemon/ceph/osd/daemon.go
Labels: backport-release-1.9, backport-release-1.10

#10983 ci: Update arm host to pick up correct self-hosted machine
  .github/workflows/daily-nightly-jobs.yml
Labels: skip-ci

#10925 docs: Simplify code owners for ceph provider
  CODE-OWNERS
Labels: skip-ci

#10912 docs: add upgrade steps for multi-tenant custer
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: skip-ci

#10992 docs: add logical volume to storage options
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
Labels: skip-ci, backport-release-1.9, backport-release-1.10

#10990 ci: add mon_data_avail_warn to canary ci test
  deploy/examples/cluster-test.yaml
Labels: backport-release-1.9, backport-release-1.10

#10942 csi: customize plugin volumes and volumemounts
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/k8sutil/volume.go
Labels: backport-release-1.10

#11012 operator: silence 'cm is handled by another watcher' DEBUG messages
  pkg/operator/ceph/cluster/predicate.go
Labels: backport-release-1.9, backport-release-1.10

#11016 docs: clarify Object Pool CRD is same as Block Pool CRD
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: skip-ci, backport-release-1.10

#11022 docs: fix indentation in CephCluster on PVC example yaml
  Documentation/CRDs/Cluster/pvc-cluster.md
Labels: backport-release-1.10

#11008 build: use script to reliably determine latest released release branch
  build/release/Makefile
  build/release/latest_release_branch.sh
Labels: build, ci

#11030 csi: make sure we reset CSIParam booleans to default
  pkg/operator/ceph/csi/csi.go
Labels: csi, backport-release-1.10

#10898 nfs: fix nfs if multus is enabled
  .github/workflows/canary-integration-test.yml
  pkg/daemon/ceph/client/command.go
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/rbd/controller.go
  pkg/operator/ceph/cluster/version.go
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/mirror/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/controller.go
  pkg/operator/ceph/object/realm/controller.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zonegroup/controller.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.10

#11004 ci: move to ubuntu 20.04 runner completely
  .github/workflows/canary-integration-test.yml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.10

#11048 osd: allow raw partitions to be picked up by discover daemon
  pkg/clusterd/disk.go
  pkg/daemon/discover/discover.go
  pkg/daemon/discover/discover_test.go
Labels: backport-release-1.9, backport-release-1.10

#11042 nfs: allow users to include additional files in the SSSD sidecar
  Documentation/CRDs/ceph-nfs-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/nfs.yaml
  design/ceph/ceph-nfs-ganesha.md
  pkg/apis/ceph.rook.io/v1/nfs.go
  pkg/apis/ceph.rook.io/v1/nfs_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/nfs/security.go
  pkg/operator/k8sutil/k8sutil.go
  pkg/operator/k8sutil/k8sutil_test.go
Labels: ceph-nfs, backport-release-1.10

#10966 operator: make imagePullPolicy customizable for csi driver and ceph pods
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/crds.yaml
  deploy/examples/operator.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/crash/crash.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/controller/version.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
Labels: backport-release-1.10

#11071 examples: CephBlockPool does not have spec.annotations
  deploy/examples/pool-ec.yaml
  deploy/examples/pool.yaml
Labels: backport-release-1.10

#11069 osd: clarify lv is not picked by filters
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  pkg/daemon/ceph/osd/daemon.go
Labels: backport-release-1.10

#11076 docs: Symlink cleanup page to the Getting Started doc folder
  Documentation/Getting-Started/.pages
  Documentation/Getting-Started/ceph-teardown.md
  Documentation/Storage-Configuration/ceph-teardown.md
Labels: skip-ci, backport-release-1.10

#11083 csi: use ceph csi v3.7.1 for rook csi driver deployment
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#11079 osd: use 256 as cryptographicLength for keys using kmip kms
  pkg/daemon/ceph/osd/kms/kmip.go
Labels: backport-release-1.10

#11017 docs: update troubleshoot docs and add krew uses
  Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md
Labels: docs, skip-ci, backport-release-1.10

#11085 update sidecars to latest in CSI deployment
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: backport-release-1.10

#10536 ci: update canary k8s version to 1.25.0
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  tests/scripts/deploy-validate-vault.sh
Labels: ci
