Repository rook/rook, pull requests merged in 2022-08, with the labels that each got.

#10659 Revert "ci: use ceph v17.2.1 instead of latest v17"
  deploy/examples/cluster-multus-test.yaml
  deploy/examples/cluster-test.yaml
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.9

#10647 csi: disable liveness sidecar by default
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: csi, backport-release-1.9

#10654 Correct indentation level for pool rules
  deploy/examples/monitoring/localrules.yaml
Labels: backport-release-1.9

#10639 csi: introduce new log level for sidecars
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: backport-release-1.9

#10668 test: Increase timeout waiting for file deletion status
  tests/integration/ceph_base_file_test.go
Labels: backport-release-1.9

#10677 external: fix cluster id naming in import-external-cluster script
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.9

#10543 [MASTER] Bugfix RBAC second cluster
  deploy/examples/common-second-cluster.yaml
Labels: stale, backport-release-1.7, backport-release-1.8, backport-release-1.9

#10673 docs: SSSD-NFS design
  deploy/examples/nfs.yaml
  design/ceph/ceph-nfs-ganesha.md
Labels: skip-ci

#10585 core: Operator to skip reconcile of mons and osds in debug mode
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: backport-release-1.9

#10701 core: skip ceph upgrade check in external cluster
  pkg/operator/ceph/cluster/rbd/controller.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/mirror/controller.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/object/controller.go
Labels: backport-release-1.9

#10708 rgw: update lib-bucket-provisioner version
  go.mod
  go.sum
Labels: object bucket claims (OBC), backport-release-1.8, backport-release-1.9

#10726 core: no need to delete v1beta cronJob during v1 deletion
  pkg/operator/ceph/cluster/crash/reconcile.go
Labels: backport-release-1.9

#10716 test: fix test pod log collector
  tests/framework/utils/k8s_helper.go
Labels: test

#10737 ci: update codespell config
  .github/workflows/codespell.yaml
  pkg/operator/ceph/object/objectstore_test.go
Labels: backport-release-1.8, backport-release-1.9

#10745 build: Update mergify for the release-1.10 branch and remove 1.6 automatic backports
  .mergify.yml
Labels: skip-ci

#10750 object: hostNetwork setting should be under spec.gateway instead of spec in the ObjectStore CRD
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.9, backport-release-1.10

#10725 docs: add examples for CephClient CRD use & libcephsqlite
  Documentation/CRDs/ceph-client-crd.md
  deploy/examples/sqlitevfs-client.yaml
Labels: backport-release-1.10

#10751 core: fix logrotate bash check and periodicity logic
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.9, backport-release-1.10

#10759 csi: update cephcsi to v3.7.0 release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
Labels: backport-release-1.10

#10503 csi: change the fsgrouppolicy for CephFS driver to "File" mode
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/betav1csidriver.go
Labels: backport-release-1.10

#10736 CSI: provide a way to supply `--setmetadata` and `--clustername` to the csi driver
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: csi, backport-release-1.10

#10774 csi: make cephcsi 3.6.0 as minimum supported version
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
Labels: backport-release-1.10

#10772 docs: update upgrade docs for v1.10
  Documentation/Upgrade/ceph-upgrade.md
  Documentation/Upgrade/rook-upgrade.md
Labels: docs, upgrade, skip-ci, backport-release-1.10

#10735 docs: add steps to convert existing cephobjectstore into multisite
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
Labels: docs, skip-ci

#10768 docs: add krew plugin to the troubleshooting docs
  .github/ISSUE_TEMPLATE/bug_report.md
  Documentation/Troubleshooting/.pages
  Documentation/Troubleshooting/ceph-toolbox.md
  Documentation/Troubleshooting/krew-plugin.md
Labels: skip-ci, backport-release-1.9, backport-release-1.10

#10795 docs: fix html rendering of nested list items -- "because markdown"
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
Labels: skip-ci, backport-release-1.9, backport-release-1.10

#10807 build: Test upgrade from 1.9 to master
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.10

#10816 build: remove psp from common.yaml generation
  build/rbac/gen-common.sh
  deploy/examples/common.yaml
Labels: build, backport-release-1.9, backport-release-1.10

#10822 core: Only log errors with v1beta1 cron job deletion
  pkg/operator/ceph/cluster/crash/crash.go
Labels: backport-release-1.9, backport-release-1.10

#10813 docs: improve documentation about documentation building
  Documentation/Contributing/documentation.md
Labels: skip-ci

#10821 rbdmirror: Rotate all rbd mirroring logs
  .commitlintrc.json
  pkg/operator/ceph/cluster/rbd/spec.go
Labels: backport-release-1.9, backport-release-1.10

#10806 docs: change [null] to []
  Documentation/Storage-Configuration/ceph-teardown.md
Labels: skip-ci, backport-release-1.10

#10779 osd: fix osd detection logic for old lsblk
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/daemon_test.go
Labels: backport-release-1.9, backport-release-1.10

#10834 build: Update min version to k8s 1.19
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Helm-Charts/operator-chart.md
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  tests/framework/installer/ceph_helm_installer.go
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_base_block_test.go
  tests/integration/ceph_base_file_test.go
Labels: backport-release-1.10

#10840 csi: use the latest sidecars for ceph csi driver
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#10804 object: gateway.port partially ignored when hostNetwork disabled
  pkg/operator/ceph/object/spec.go
Labels: backport-release-1.9, backport-release-1.10

#10848 ci: Revert ibm canary test to ubuntu 18
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-tests-on-release.yaml
Labels: backport-release-1.10
