Repository rook/rook, pull requests merged in 2023-09, with the labels that each got.

#12791 core: restart ceph daemons when network updated
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/spec.go
Labels: backport-release-1.12

#12770 osd: replace existing OSDs to use new store
  cmd/rook/ceph/osd.go
  pkg/daemon/ceph/client/deviceclass.go
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/remove.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/health.go
  pkg/operator/ceph/cluster/osd/health_test.go
  pkg/operator/ceph/cluster/osd/integration_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/replace.go
  pkg/operator/ceph/cluster/osd/replace_test.go
Labels: backport-release-1.12

#12844 Fix discover daemonset default value for discovery interval
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  pkg/operator/discover/discover.go
Labels: backport-release-1.12

#12778 multus: allow using NADs without inspectable CIDRs
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  pkg/apis/ceph.rook.io/v1/cluster.go
  pkg/apis/ceph.rook.io/v1/network.go
  pkg/apis/ceph.rook.io/v1/network_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/mon/node_test.go
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/rbd/spec.go
  pkg/operator/ceph/config/config.go
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/config/network.go
  pkg/operator/ceph/config/network_test.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/controller/network.go
  pkg/operator/ceph/controller/network_test.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mirror/spec.go
  pkg/operator/ceph/nfs/spec.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/k8sutil/cmdreporter/cmdreporter.go
  pkg/operator/k8sutil/network.go
  pkg/operator/k8sutil/network_test.go
Labels: backport-release-1.12

#12829 ci: use dependabot group feature
  .github/dependabot.yml
Labels: ci

#12872 helm: update docs/comments to reflect reef support
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
Labels: skip-ci, backport-release-1.12

#12875 docs: Remove skip-ci from pr checklist
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-ci

#12874 docs: Update roadmap for 1.13
  ROADMAP.md
Labels: skip-ci

#12886 exporter: bind to all interfaces if IPv6 is enabled
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
Labels: backport-release-1.12

#12894 docs: Fine tune roadmap for 1.13
  ROADMAP.md
Labels: skip-ci

#12895 mgr: Allow more than two mgrs
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/mgr/mgr.go
Labels: backport-release-1.12

#12898 build: update s5cmd to version v2.2.1
  .github/workflows/canary-integration-test.yml
  images/ceph/Makefile
Labels: backport-release-1.12

#12715 osd: make osd pod to sleep when osds are flapping
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: backport-release-1.12

#12922 test: update multus canary test
  .github/workflows/canary-integration-test.yml
  tests/scripts/github-action-helper.sh
  tests/scripts/validate_cluster.sh
Labels: backport-release-1.12

#12781 build: upgrade controller runtime to 0.16
  go.mod
  go.sum
  pkg/operator/ceph/cr_manager.go
Labels: backport-release-1.12

#12924 osd: support encrypted OSD on partiton
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: ceph-osd, backport-release-1.12

#12921 docs: Review the teardown guide for updated guidelines
  Documentation/Storage-Configuration/ceph-teardown.md
Labels: backport-release-1.12

#12932 suppress snyk warnings for MPL license projects.
  .github/workflows/snyk.yaml
  .snyk
Labels: skip-ci

#12954 ci: fix the snyk policy to correctly ignore the MPL license issue.
  .snyk
Labels: skip-ci

#12948 ci: Skip encryption pvc kms test if needed
  .github/workflows/canary-integration-test.yml
Labels: skip-ci

#12956 ci: Suppress mpl-2.0 warnings in Snyk scan
  .snyk
Labels: skip-ci

#12958 docs: krew is wrong word use kubectl instead
  .github/ISSUE_TEMPLATE/bug_report.md
  Documentation/Contributing/development-flow.md
  Documentation/Getting-Started/glossary.md
  Documentation/Getting-Started/quickstart.md
  Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md
  Documentation/Troubleshooting/.pages
  Documentation/Troubleshooting/ceph-toolbox.md
  Documentation/Troubleshooting/disaster-recovery.md
  Documentation/Troubleshooting/kubectl-plugin.md
  design/common/multi-net-multus.md
Labels: docs, skip-ci

#12971 ci: remove workaround for clean disk action
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.11, backport-release-1.12
