Repository rook/rook, pull requests merged in 2023-01, with the labels that each got.

#11483 osd: add expand-bluefs init container for host-based cluster
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: backport-release-1.10

#11493 external: Dont call telemetry if the cluster is external
  pkg/operator/ceph/cluster/cluster.go
Labels: backport-release-1.10

#11127 helm: fix toolbox command, default to cluster image
  Documentation/Helm-Charts/ceph-cluster-chart.md
  deploy/charts/rook-ceph-cluster/templates/deployment.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
  tests/framework/installer/ceph_helm_installer.go
Labels: backport-release-1.10

#11407 docs: add a design doc proposal for mon zonal availability support
  design/ceph/ceph-mon-pv.md
Labels: skip-ci

#11506 docs: fix grafana dashboard links
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
Labels: skip-ci, backport-release-1.10

#11512 docs: add limitRange comment to deploy/charts/rook-ceph-cluster/values.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: skip-ci, backport-release-1.10

#11510 csi: update sidecars to latest release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#11517 helm: storageclass secrets namespace made the same as the release namespace
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.10

#11497 object: Move bucket notifications to stable
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
  PendingReleaseNotes.md
Labels: skip-ci

#11523 ceph: set rbd_default_map_options for encryption
  pkg/operator/ceph/cluster/cluster.go
  tests/framework/installer/ceph_manifests.go
Labels: backport-release-1.10

#11532 webhook: disable webhook by default
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/webhook.go
  tests/framework/installer/ceph_settings.go
Labels: backport-release-1.10

#11529 docs: fix incorrect CRD name in documentation
  design/ceph/resource-constraints.md
Labels: skip-ci

#11546 docs: fix ceph cluster crd list indentation issue
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-zone-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-fs-mirror-crd.md
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/ceph-client-crd.md
  Documentation/CRDs/ceph-nfs-crd.md
Labels: docs, skip-ci, backport-release-1.10

#11543 docs: remove health checker related option in object-external.yaml
  deploy/examples/object-external.yaml
Labels: docs, skip-ci, backport-release-1.10

#11542 test: update kv version for rgw-kms tests
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.10

#11556 csi: fix custom ceph.conf for csi pods
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.10

#11538 mgr: role rook-ceph-mgr is lack of patch verb to compete ceph request(fix 11537)
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/examples/common.yaml
Labels: backport-release-1.10

#11560 docs: add release instructions
  build/release/README.md
Labels: docs, skip-ci

#11120 test: add multisite bidirectional replication coverage
  .github/workflows/rgw-multisite-test/action.yml
  tests/scripts/github-action-helper.sh
Labels: test, ceph-rgw, ci

#11577 csi: add default version to images if it is missing
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/csi/util_test.go
Labels: backport-release-1.10

#11453 Fix CephFS Status updates
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/status.go
Labels: backport-release-1.10

#11318 docs: design document for multi-cluster service support
  design/ceph/multi-cluster-service.md
Labels: skip-ci
