Repository rook/rook, pull requests merged in 2023-02, with the labels that each got.

#11601 docs: add export path example for NFS CSI
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
Labels: docs, ceph-nfs, skip-ci, backport-release-1.10

#11593 operator: fix webhook logging during deletion
  pkg/operator/ceph/webhook-config.go
Labels: backport-release-1.10

#11505 helm: document installing different types of CephClusters
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.10

#11621 docs: fix formatting issues
  Documentation/Storage-Configuration/Monitoring/ceph-dashboard.md
Labels: docs, skip-ci, backport-release-1.10

#11620 docs: fixing build instructions
  Documentation/Contributing/development-flow.md
Labels: skip-ci, backport-release-1.10

#11611 mds: support mds with multus
  pkg/operator/ceph/file/mds/spec.go
Labels: backport-release-1.10

#11525 docs: add glossary page
  Documentation/Getting-Started/.pages
  Documentation/Getting-Started/glossary.md
Labels: skip-ci

#11646 test: change ceph version of osd on pvc canary test to avoid failures
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: backport-release-1.9, backport-release-1.10

#11625 csi: provide way to set cephfs kernel mount options
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
Labels: csi

#11616 helm: Add labels and annotations to config overrides configmap
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/utils.go
  pkg/operator/ceph/cluster/utils_test.go
Labels: backport-release-1.10

#11630 rgw: handle insecure flag skip for object bucket notification in the tls config
  pkg/operator/ceph/object/notification/provisioner.go
Labels: backport-release-1.10

#11662 Add comment regarding placement restrictions.
  deploy/examples/filesystem.yaml
Labels: skip-ci, backport-release-1.10

#11594 rbdmirror: set log rotation from 7 to 4x i.e 28
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: backport-release-1.10

#11436 ci: Update min K8s support to 1.21 and add 1.26 support
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  tests/scripts/github-action-helper.sh
Labels: ci

#11643 mgr: use k8s readiness probe to implement mgr HA
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: ceph-mgr

#11678 core: set rbd default map options
  pkg/operator/ceph/cluster/cluster.go
Labels: do-not-merge

#11673 object: RGW metadata pg count reduction on 16.2.11
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
Labels: backport-release-1.10

#11674 osd: Ensure rook version label is not set on pod
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/k8sutil/k8sutil.go
Labels: backport-release-1.10

#11687 ci: Update mergify for the 1.11 branch
  .mergify.yml
Labels: skip-ci

#11631 csi: add support for enabling read affinity for rbd volumes.
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
  pkg/operator/ceph/cluster/osd/topology/topology_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
Labels: backport-release-1.11

#11690 ci: fix MultiClusterDeploySuite CI
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/k8sutil/deployment.go
Labels: backport-release-1.11

#11668 build: clean rbac which are not required
  .github/workflows/build.yml
  Makefile
  build/csv/csv-gen.sh
  deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
  deploy/examples/common.yaml
  deploy/olm/assemble/metadata-common.yaml
  images/ceph/Makefile
Labels: backport-release-1.11

#11697 csi: add missing node access to cephfs driver
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.10, backport-release-1.11

#11013 helm: support setting storageclass volumeBindingMode in rook-ceph-cluster helm chart
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.11

#11713 build: update package dependencies
  go.mod
  go.sum
Labels: backport-release-1.11

#11723 mgr: Wait for the mgr pod to be running after an update
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/k8sutil/deployment.go
  pkg/operator/k8sutil/pod.go
Labels: backport-release-1.11

#11724 build: fix csv generation during make build
  Makefile
Labels: backport-release-1.11

#11728 docs: update docs to prepare for v1.11 release
  Documentation/Upgrade/ceph-upgrade.md
  Documentation/Upgrade/rook-upgrade.md
Labels: docs, skip-ci, backport-release-1.11

#11716 object: update os user caps
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
Labels: bug, backport-release-1.10, backport-release-1.11

#11734 doc: add helm supported version note to upgrade doc
  Documentation/Upgrade/rook-upgrade.md
Labels: docs, skip-ci, backport-release-1.11

#11661 mgr: remove legacy mgr HA logic and watch-active sidecar
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  cmd/rook/ceph/ceph.go
  cmd/rook/ceph/mgr.go
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
  deploy/examples/monitoring/service-monitor.yaml
  pkg/apis/ceph.rook.io/v1/resources.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/dashboard_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mgr/spec_test.go
Labels: backport-release-1.11

#11738 csi: update cephcsi to v3.8.0
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
  Documentation/Upgrade/rook-upgrade.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
Labels: backport-release-1.11

#11747 build: allow building on Mac with Apple silicon
  build/makelib/common.mk
Labels: build, backport-release-1.10, backport-release-1.11

#11745 test: Increase timeout waiting for ceph commands
  .github/workflows/canary-integration-test.yml
  .mergify.yml
  tests/scripts/collect-logs.sh
  tests/scripts/validate_cluster.sh
Labels: backport-release-1.11

#11740 build: use Kube v1.26.1 API and in CI
  .github/workflows/canary-integration-test.yml
  Documentation/Upgrade/rook-upgrade.md
  Makefile
  build/crds/build-crds.sh
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/daemon/ceph/client/mirror.go
  pkg/operator/ceph/cluster/cleanup.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/create_test.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/object/objectstore.go
  pkg/util/exec/exec_pod.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.11

#11762 docs: update k8s version to 1.26.1 in release notes
  PendingReleaseNotes.md
Labels: skip-ci

#11578 Support multi cluster service
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/cluster.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/service.go
  pkg/operator/ceph/cluster/mon/service_test.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/k8sutil/service.go
Labels: backport-release-1.11

#11567 osd: handle device name change and device removel correctly
  pkg/operator/ceph/cluster/osd/spec.go
Labels: keepalive, backport-release-1.10, backport-release-1.11

#11772 doc: use kubectl replace instead of apply for crd updates
  Documentation/Upgrade/rook-upgrade.md
Labels: docs, skip-ci, backport-release-1.11

#11778 ci: Enable snyk flag not to build vcs
  .github/workflows/synk.yaml
Labels: skip-ci, backport-release-1.11

#11760 core: on crash pod ensure rook version label is not set
  pkg/operator/ceph/cluster/nodedaemon/crash.go
  pkg/operator/ceph/cluster/nodedaemon/crash_test.go
Labels: backport-release-1.10, backport-release-1.11
