Repository rook/rook, pull requests merged in 2023-06, with the labels that each got.

#12314 ci: Daily rgw tests to run against ceph main
  .github/workflows/daily-nightly-jobs.yml
Labels: skip-ci

#12299 core: empty ceph-daemons-sock-dir for osd onPVC
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
Labels: backport-release-1.11

#12213 doc: update external cluster docs
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/charts/rook-ceph-cluster/values-external.yaml
Labels: skip-ci, backport-release-1.11

#12337 mgr: removing unnecessary rook-ceph-mgr rbac entries
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/examples/common.yaml
Labels: backport-release-1.11

#12217 fix: typo in logs to print fullname of CephCluster
  pkg/operator/ceph/controller/controller_utils.go
Labels: backport-release-1.11

#12334 docs: prevent to delete other clusters data on cluster deletion
  Documentation/Storage-Configuration/ceph-teardown.md
Labels: docs, skip-ci, backport-release-1.11

#12220 nfs: Add Spec.Security.Kerberos.DomainName to the CRD to configure /etc/idmapd.conf
  Documentation/CRDs/ceph-nfs-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/NFS/nfs-security.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/nfs/security.go
Labels: backport-release-1.11

#12360 pool: Add .mgr pool to the stretch cluster examples
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
Labels: skip-ci, backport-release-1.11

#12324 helm: add EC Block Pool config in helm chart
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.11

#11722 docs: suggest qemu driver for minikube on apple silicon
  Documentation/Contributing/development-environment.md
Labels: docs, stale, skip-ci, backport-release-1.11

#12368 docs: remove the line generated by gen-crd-api-reference-docs
  Documentation/CRDs/specification.md
  Documentation/gen-crd-api-reference-docs/template/pkg.tpl
  build/crds/generate-crd-docs.sh
Labels: docs

#11995 docs: add design doc for Ceph COSI driver
  design/ceph/object/ceph-cosi-driver.md
Labels: docs, skip-ci

#12253 docs: design doc for node loss
  design/ceph/node-loss-rbd-cephfs.md
Labels: docs, design, skip-ci

#12372 operator:Add ceph image version label to PVC
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  pkg/operator/ceph/cluster/osd/labels.go
Labels: ceph-osd, backport-release-1.11

#12341 object : add ssl ref in cephobjectstore user secret
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.11

#12406 Fix confusing successful message when reconciling CephObjectStoreUser
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.11

#12252 docs: update storage architecture diagram
  Documentation/Getting-Started/ceph-storage/Rook High-Level Architecture.drawio
  Documentation/Getting-Started/ceph-storage/Rook High-Level Architecture.png
  Documentation/Getting-Started/ceph-storage/kubernetes.png
  Documentation/Getting-Started/storage-architecture.md
Labels: docs, skip-ci

#12430 exporter: Ignore failed deletion of service monitor
  .commitlintrc.json
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
  pkg/operator/k8sutil/prometheus.go
Labels: backport-release-1.11

#12417 external: make import script idempotent
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.11

#12437 Multus Validation : Added verbs "deletecollection"
  deploy/charts/rook-ceph/templates/role.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.11
