Repository rook/rook, pull requests merged in 2023-05, with the labels that each got.

#12151 ci: disable multi-cluster-mirroring
  .github/workflows/canary-integration-test.yml
Labels: backport-release-1.11

#12159 docs: Update the PR template for a typo and more easily discoverable dev guide link
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-ci

#12161 core: update k8s module to latest version
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
Labels: go, backport-release-1.11

#12069 test: add multus validation test routine to rook binary
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  cmd/rook/ceph/ceph.go
  cmd/rook/discover.go
  cmd/rook/main.go
  cmd/rook/rook/rook.go
  cmd/rook/secret.go
  cmd/rook/userfacing/multus/multus.go
  cmd/rook/userfacing/multus/validation/validation.go
  cmd/rook/userfacing/userfacing.go
  cmd/rook/util/cmdreporter.go
  cmd/rook/util/copybins.go
  design/common/multi-homed-cluster.md
  design/common/multi-net-multus.md
  go.mod
  go.sum
  pkg/daemon/multus/client-daemonset.yaml
  pkg/daemon/multus/nginx-config.yaml
  pkg/daemon/multus/nginx-pod.yaml
  pkg/daemon/multus/resources.go
  pkg/daemon/multus/statemachine.go
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/util.go
  pkg/daemon/multus/validation.go
  tests/scripts/multus-test.sh
Labels: test, multus, backport-release-1.11

#12110 docs: add support for autogenerated docs for CRDs
  .github/workflows/docs-check.yml
  Documentation/CRDs/.pages
  Documentation/CRDs/specification.md
  Documentation/gen-crd-api-reference-docs/template/members.tpl
  Documentation/gen-crd-api-reference-docs/template/pkg.tpl
  Documentation/gen-crd-api-reference-docs/template/placeholder.go
  Documentation/gen-crd-api-reference-docs/template/type.tpl
  Makefile
  build/crds/generate-crd-docs.sh
  crd-docs-config.json
  pkg/apis/ceph.rook.io/v1/types.go
Labels: docs

#12179 docs: update documentation for CRDs
  Documentation/CRDs/specification.md
Labels: docs

#12180 docs: fix slack image in rook readme
  README.md
Labels: skip-ci

#12181 ceph: unset all the encryption configuration before setting
  pkg/operator/ceph/config/monstore.go
Labels: backport-release-1.11

#12186 operator: fix package logger name for rookcli
  cmd/rook/rook/rook.go
Labels: backport-release-1.11

#12187 operator: validate multus validation networks in cli
  cmd/rook/userfacing/multus/validation/validation.go
Labels: backport-release-1.11

#12192 operator: use KUBECONFIG context for cli if present
  cmd/rook/rook/rook.go
  cmd/rook/userfacing/multus/validation/validation.go
Labels: backport-release-1.11

#12194 core: disable controller runtime metrics server
  pkg/operator/ceph/cr_manager.go
Labels: backport-release-1.11

#12202 docs: correct link for helm.sh file
  Documentation/Contributing/development-environment.md
Labels: docs, skip-ci

#12193 monitoring: Configurable option to disable prometheus metrics
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  design/ceph/ceph-exporter.md
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: backport-release-1.11

#12170 servicemonitor for rook-ceph csi drivers
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/servicemonitor.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.11

#12200 docs: Update the roadmap for v1.12
  ROADMAP.md
Labels: skip-ci

#12215 core: add termination grace period for exporter pods
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: backport-release-1.11, ceph-exporter

#12216 monitoring: Skip creating the service monitor for the exporter if monitoring is not enabled
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: backport-release-1.11

#12164 osd: Support expanding lvm osd on pvc
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: backport-release-1.11

#12204 docs: update the documentation for external rgw servers
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
Labels: skip-ci

#12224 docs: Dev guide review updates
  Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
  Documentation/Contributing/development-flow.md
  pkg/operator/ceph/cluster/cluster_external.go
Labels: skip-ci, backport-release-1.11

#12247 rbdmirror: Retry reconcile if cluster not initialized
  pkg/operator/ceph/cluster/rbd/controller.go
Labels: backport-release-1.11

#11598 nfs: adding RGW section in ganesha.conf
  Documentation/Storage-Configuration/NFS/nfs-advanced.md
  pkg/operator/ceph/nfs/config.go
Labels: stale

#12211 operator: pull multus validation test images before test
  cmd/rook/userfacing/multus/validation/validation.go
  pkg/daemon/multus/client-daemonset.yaml
  pkg/daemon/multus/image-pull-daemonset.yaml
  pkg/daemon/multus/nginx-pod.yaml
  pkg/daemon/multus/resources.go
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/validation.go
Labels: backport-release-1.11

#12268 monitoring: Service monitor should not use mgr_role label
  deploy/examples/monitoring/service-monitor.yaml
Labels: backport-release-1.11

#12231 test: allow specifying custom nginx image for multus validation
  cmd/rook/userfacing/multus/validation/validation.go
  pkg/daemon/multus/client-daemonset.yaml
  pkg/daemon/multus/image-pull-daemonset.yaml
  pkg/daemon/multus/nginx-pod.yaml
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/validation.go
Labels: test, backport-release-1.11

#12273 object: add missing cephcluster spec addition in object controller
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/topic/provisioner.go
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.11

#12293 mgr: update default rook_cluster of ServiceMonitor
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/k8sutil/prometheus.go
  pkg/operator/k8sutil/prometheus_test.go
Labels: ceph, operator, monitoring, backport-release-1.11

#12302 core: use -default-* flags
  pkg/operator/ceph/config/defaults.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/ceph/test/containers.go
Labels: logs, backport-release-1.11

#12251 helm: add exporter resource entry to ceph cluster
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
Labels: docs, helm, skip-ci, backport-release-1.11

#12256 object: add missing caps for object store user
  Documentation/CRDs/Object-Storage/ceph-object-store-user-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
Labels: backport-release-1.11

#12282 test: add CI e2e test for multus validation test
  .github/workflows/multus.yaml
  pkg/daemon/multus/client-daemonset.yaml
  tests/scripts/multus/default-public-cluster-nads.yaml
  tests/scripts/multus/kind-config.yaml
  tests/scripts/multus/setup-multus.sh
Labels: test, multus, ci, backport-release-1.11, debug-ci

#12270 Add PITS Global Data Recovery Services to the list of adopters
  ADOPTERS.md
Labels: skip-ci

#12264 external: fqdn should be persisted
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/object-external.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.11
