Repository rook/rook, pull requests merged in 2023-08, with the labels that each got.

#12615 docs: add note in upgrade guide about cephfs driver's breaking change
  Documentation/Upgrade/rook-upgrade.md
Labels: csi, backport-release-1.12

#12640 ci: Run object suite in master and release branches
  .github/workflows/integration-tests-on-release.yaml
Labels: skip-ci, backport-release-1.12

#12644 docs: Reset the pending release notes for v1.13
  PendingReleaseNotes.md
Labels: skip-ci

#12659 ci: add free disk action to release/master ci
  .github/workflows/integration-tests-on-release.yaml
Labels: skip-ci

#12605 helm: additional ServiceMonitor labels
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/servicemonitor.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.12

#12624 object: fix s5cmd for s3 endpoint verification
  .github/workflows/canary-integration-test.yml
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/examples/toolbox-operator-image.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.12

#12666 operator: fix formatting of some logger methods
  pkg/operator/ceph/nfs/config.go
  pkg/operator/ceph/object/realm/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: backport-release-1.11, backport-release-1.12

#12678 csi: add maxUnavailable for cephfs csi daemonset
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
Labels: backport-release-1.12

#12694 ci: update the objectsuite test timeout to 40m
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
Labels: backport-release-1.12

#12495 multus: Add sample job manifest for multus config validation
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  deploy/examples/multus-validation.yaml
Labels: backport-release-1.12

#12698 nfs: run dbus-daemon sidecar as dbus user instead of root
  pkg/operator/ceph/nfs/spec.go
Labels: backport-release-1.12

#12725 file: ignore exit code 22 when addding datapool
  pkg/daemon/ceph/client/filesystem.go
Labels: backport-release-1.12

#12675 helm: install rook in openshift cluster
  Documentation/Getting-Started/ceph-openshift.md
  deploy/charts/rook-ceph-cluster/templates/securityContextConstraints.yaml
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
Labels: backport-release-1.12

#12679 operator: log op. config cm setting when changed
  pkg/operator/k8sutil/configmap.go
  pkg/operator/k8sutil/configmap_test.go
Labels: backport-release-1.12

#12672 build: update vault and other indirect imports
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/nodedaemon/crash_test.go
  pkg/operator/ceph/controller/spec.go
Labels: backport-release-1.12

#12731 monitoring: add "for" to CephOSDDownHigh alert
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
Labels: backport-release-1.12

#12743 tests: Start toolbox earlier in tests
  tests/framework/installer/ceph_installer.go
  tests/integration/ceph_multi_cluster_test.go
Labels: backport-release-1.12

#12384 mon: add mon storage class support
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/cluster.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/mon/spec.go
Labels: backport-release-1.12

#12744 docs: move how to run tests instructions to contributing
  Documentation/Contributing/rook-test-framework.md
Labels: docs, skip-ci

#12747 helm: replaced broken documentation references
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.12

#12734 helm: improvement in docs
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  build/makelib/helm.mk
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.12

#12724 csi: set ceph cluster as ControllerRef for holder ds
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/spec_test.go
Labels: backport-release-1.12

#12663 build: update go modules
  go.mod
  go.sum
Labels: backport-release-1.12

#12774 Multus validation job automated update
  .github/workflows/docs-check.yml
  Makefile
  build/deploy/generate-deploy-examples.sh
  deploy/examples/multus-validation.yaml
Labels: skip-ci, backport-release-1.12

#12598 docs: correct some libcephsqlite statements
  Documentation/CRDs/ceph-client-crd.md
Labels: stale, skip-ci, backport-release-1.12

#12797 ceph: return valid CIDR ip
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: backport-release-1.12

#12808 mon: typo in json tag of struct MonMap
  pkg/daemon/ceph/client/status.go
Labels: backport-release-1.12

#12814 cleanup of the OSD migration design document
  design/ceph/osd-migration.md
Labels: docs

#12811 external: change cluster_name to k8s_cluster_name
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.12

#12804 object: avoid creating same bucket for two different OBC
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
Labels: backport-release-1.11, backport-release-1.12
