Repository rook/rook, pull requests merged in 2023-07, with the labels that each got.

#12143 external: add support for IPV6 ceph daemons
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.11

#12295 security: remove default scc privileges
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/toolbox.yaml
  pkg/apis/ceph.rook.io/v1/scc.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: security

#12462 csi: update csi holder daemonset template
  pkg/operator/ceph/csi/spec.go
Labels: csi, multus, backport-release-1.11

#12489 ci: Enable mergify for the 1.12 branch
  .mergify.yml
Labels: skip-ci

#12492 core: add check for pv access modes' multinode support
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: backport-release-1.12

#12423 test: add support Ceph Reef v18 with updated integration tests
  .github/workflows/daily-nightly-jobs.yml
  deploy/examples/cluster-test.yaml
  pkg/operator/ceph/cluster/version_test.go
  pkg/operator/ceph/version/version.go
  pkg/operator/ceph/version/version_test.go
  tests/framework/installer/ceph_installer.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.12

#12477 external: pin the default csi subvolume
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.11, backport-release-1.12

#12327 Add option to disable synchronization traffic for RGWs
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/rgw.go
  pkg/operator/ceph/object/rgw_test.go
Labels: backport-release-1.12

#12530 test: update reef as default version
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.12

#12502 external: support custom ceph keyring file
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.11, backport-release-1.12

#12415 object: adding ceph cosi driver
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  PendingReleaseNotes.md
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/clusterrolebinding.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/charts/rook-ceph/templates/serviceaccount.yaml
  deploy/examples/common.yaml
  deploy/examples/cosi/bucketaccess.yaml
  deploy/examples/cosi/bucketaccessclass.yaml
  deploy/examples/cosi/bucketclaim.yaml
  deploy/examples/cosi/bucketclass.yaml
  deploy/examples/cosi/cephcosidriver.yaml
  deploy/examples/cosi/cosi-user.yaml
  deploy/examples/crds.yaml
  deploy/examples/images.txt
  images/ceph/Makefile
  pkg/apis/ceph.rook.io/v1/register.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/cephcosidriver.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_ceph.rook.io_client.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/fake/fake_cephcosidriver.go
  pkg/client/clientset/versioned/typed/ceph.rook.io/v1/generated_expansion.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/cephcosidriver.go
  pkg/client/informers/externalversions/ceph.rook.io/v1/interface.go
  pkg/client/informers/externalversions/generic.go
  pkg/client/listers/ceph.rook.io/v1/cephcosidriver.go
  pkg/client/listers/ceph.rook.io/v1/expansion_generated.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/object/cosi/controller.go
  pkg/operator/ceph/object/cosi/controller_test.go
  pkg/operator/ceph/object/cosi/spec.go
  tests/framework/clients/bucket.go
  tests/framework/clients/cosi.go
  tests/framework/clients/test_client.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_base_object_test.go
  tests/integration/ceph_cosi_test.go
  tests/integration/ceph_object_test.go
  tests/integration/ceph_upgrade_test.go
  tests/scripts/github-action-helper.sh
Labels: object, object-cosi, backport-release-1.12

#12460 object: align spelling of user admin capabilities with ceph
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.11, backport-release-1.12

#12548 cosi: The COSI driver should be disabled by default
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
  pkg/operator/ceph/object/cosi/controller.go
  pkg/operator/ceph/object/cosi/controller_test.go
Labels: backport-release-1.12

#12508 external: create ceph cluster namespace
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.11, backport-release-1.12

#12562 object: update ceph cosi driver image to v0.1.1
  deploy/examples/images.txt
  pkg/operator/ceph/object/cosi/spec.go
Labels: object-cosi, backport-release-1.12

#12575 core: force delete rook-ceph-exporter pod
  pkg/operator/ceph/cluster/cephstatus.go
  pkg/operator/ceph/cluster/cephstatus_test.go
Labels: backport-release-1.12

#12466 osd: configure backend store
  Documentation/CRDs/specification.md
  cmd/rook/ceph/osd.go
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/storage.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/cluster/osd/config/config.go
  pkg/operator/ceph/cluster/osd/envs.go
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/spec.go
Labels: ceph-osd, backport-release-1.12

#12560 object: do not add objectstore endpoint to zone when sync is disabled
  pkg/operator/ceph/object/objectstore.go
Labels: backport-release-1.12

#12564 test: collect kube-system logs for debugging
  tests/framework/clients/filesystem.go
  tests/scripts/collect-logs.sh
Labels: backport-release-1.12

#12517 nfs: mount krb5.conf and krb5.keytab in the sssd container
  pkg/operator/ceph/nfs/security.go
Labels: backport-release-1.12

#12617 nfs: fix null pointer deref in generateSssdSidecarResources()
  pkg/operator/ceph/nfs/security.go
Labels: backport-release-1.12

#12534 external: added an optional flag for enabling v2 mon port
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: do-not-merge

#12625 tests: Toolbox to use same ceph image as the test
  .commitlintrc.json
  tests/framework/installer/ceph_manifests.go
Labels: backport-release-1.12
