Repository rook/rook, pull requests merged in 2023-10, with the labels that each got.

#12970 core: use crash profile in crash daemon keyring
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
Labels: backport-release-1.12

#12981 file: Disable active standby when set to false
  pkg/daemon/ceph/client/filesystem.go
  pkg/operator/ceph/file/filesystem.go
Labels: backport-release-1.12

#12988 docs: fixing some spelling issues
  .github/workflows/canary-integration-test.yml
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
  Documentation/Storage-Configuration/ceph-teardown.md
  cmd/rook/rook/rook.go
  deploy/examples/create-external-cluster-resources.py
  pkg/daemon/multus/validation.go
  pkg/operator/ceph/object/admin.go
  tests/framework/clients/block.go
Labels: skip-ci

#12986 ci: fixing linter error (using variable 'urllib' before assignment)
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.12

#12997 ci: make use of caching in actions/setup-go
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/multus.yaml
  .github/workflows/rbac-gen.yaml
Labels: backport-release-1.12

#12968 multus: allow node profiles in validation test
  .github/workflows/multus.yaml
  cmd/rook/userfacing/multus/validation/config.go
  cmd/rook/userfacing/multus/validation/validation.go
  deploy/examples/multus-validation.yaml
  pkg/daemon/multus/client-daemonset.yaml
  pkg/daemon/multus/config.go
  pkg/daemon/multus/config.yaml
  pkg/daemon/multus/config_test.go
  pkg/daemon/multus/image-pull-daemonset.yaml
  pkg/daemon/multus/nginx-pod.yaml
  pkg/daemon/multus/resources.go
  pkg/daemon/multus/resources_test.go
  pkg/daemon/multus/templates.go
  pkg/daemon/multus/validation.go
  tests/scripts/multus/kind-config.yaml
  tests/scripts/multus/stretch.yaml
  tests/scripts/multus/test-110-cli.sh
  tests/scripts/multus/test-200-stretch-label-nodes.sh
  tests/scripts/multus/test-200-stretch-taint-nodes.sh
  tests/scripts/multus/test-210-stretch-overlap.sh
  tests/scripts/multus/test-211-stretch-cleanup.sh
  tests/scripts/multus/test-220-stretch-pub-and-cluster.sh
  tests/scripts/multus/test-230-stretch-pub-only.sh
  tests/scripts/multus/test-240-stretch-cluster-only.sh
Labels: backport-release-1.12

#13001 external: fix client.healthchecker user keyring return
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.12

#12998 exporter: Change verbose info to debug logs
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: backport-release-1.12

#13008 docs: fixing typos
  Documentation/Contributing/development-environment.md
Labels: backport-release-1.12

#13011 csi: add mountinfo path for cephfs daemonset
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
Labels: backport-release-1.12

#12860 mds: improve the mds liveness probe calls
  .github/workflows/unit-test.yml
  pkg/operator/ceph/file/mds/livenessprobe.go
  pkg/operator/ceph/file/mds/livenessprobe.sh
  pkg/operator/ceph/file/mds/livenessprobe_test.go
  pkg/operator/ceph/file/mds/mds.go
  pkg/operator/ceph/file/mds/spec.go
  pkg/operator/ceph/file/mds/spec_test.go
  pkg/operator/ceph/file/mds/test/0FS-2MDS.json
  pkg/operator/ceph/file/mds/test/0FS.json
  pkg/operator/ceph/file/mds/test/1FS-2MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(0,0)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(0,2)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(1,2)MDS.json
  pkg/operator/ceph/file/mds/test/2FS-(2,2)MDS.json
Labels: backport-release-1.12

#13033 mon: Write the assimilate-conf config to a valid operator working directory
  pkg/operator/ceph/config/monstore.go
  pkg/operator/ceph/config/monstore_test.go
Labels: backport-release-1.12

#13039 csi: fix indentation for mountinfo
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin.yaml
Labels: backport-release-1.12

#12165 osd: prevent to fallback to lvm mode in osd on lvm creation
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: ceph-osd, keepalive, stale, backport-release-1.12

#13028 cosi: fix problem in cosi document
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
Labels: docs

#13046 osd: print warning message if no matching node found for osd
  pkg/operator/k8sutil/node.go
Labels: backport-release-1.12

#13050 docs: adding specific instructions to upgrade Rook toolbox
  Documentation/Upgrade/ceph-upgrade.md
Labels: skip-ci, backport-release-1.12

#13061 external: automatically init the rbd pool
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.12

#13072 core: Crash collector keyring requires rw access for the mgr profile
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
Labels: backport-release-1.12

#13078 namespace: adding namespace to all rook-ceph namespaces references
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/dashboard-external-http.yaml
  deploy/examples/dashboard-external-https.yaml
  deploy/examples/dashboard-loadbalancer.yaml
  deploy/examples/monitoring/exporter-service-monitor.yaml
  deploy/examples/monitoring/service-monitor.yaml
  deploy/examples/nfs-load-balancer.yaml
  deploy/examples/osd-env-override.yaml
  deploy/examples/pool-mirrored.yaml
  deploy/examples/sqlitevfs-client.yaml
  deploy/examples/volume-replication-class.yaml
Labels: backport-release-1.12

#13094 security: update snyk ignores for MPL-2.0
  .snyk
Labels: skip-ci

#13096 test: add govulncheck to look for go vulnerabilities
  .github/workflows/golangci-lint.yaml
Labels: test, security, ci

#13060 external: fix monitoring endpoint check
  deploy/examples/create-external-cluster-resources-tests.py
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.12

#13089 docs: unifying namespaces handling for the second cluster creation
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
  deploy/examples/common-second-cluster.yaml
Labels: backport-release-1.12

#13099 doc: update lvm prerequisites
  Documentation/Getting-Started/Prerequisites/prerequisites.md
Labels: skip-ci

#13105 ci: skip csv generation for mac
  build/csv/csv-gen.sh
Labels: ci

#12166 doc: add the table to know supported osd configuration
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Getting-Started/quickstart.md
Labels: keepalive, skip-ci, backport-release-1.12

#13114 pool: rbd cmd shouldn't use admin in external mode
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: backport-release-1.12

#13101 test: adding a script to simplify test cluster creation
  Documentation/Contributing/development-environment.md
  tests/scripts/create-dev-cluster.sh
Labels: skip-ci

#12952 mon: failover mons from hostpath to persistent volumes
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
Labels: backport-release-1.12

#13115 test: adding an example for cluster on local pvc creation
  deploy/examples/cluster-on-pvc-minikube.yaml
Labels: skip-ci

#13128 ci: Update helm linter to v2.6.0
  .github/workflows/helm-lint.yaml
Labels: skip-ci

#13125 docs: add namespace on delete webhook command
  Documentation/Troubleshooting/disaster-recovery.md
Labels: backport-release-1.12
