Repository rook/rook, pull requests merged in 2023-03, with the labels that each got.

#11797 ceph: add osd container ports only if mcs is enabled
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.11

#11808 docs: change old version hint in docs
  .docs/overrides/main.html
Labels: docs, skip-ci, backport-release-1.10, backport-release-1.11

#11665 object: make OBC genUserID unique across clusters
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/rgw-handlers.go
Labels: object bucket claims (OBC), backport-release-1.10, backport-release-1.11

#11818 ci: Fix the multus integration test
  .github/workflows/canary-integration-test.yml
  .github/workflows/canary-test-config/action.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.11

#11804 manifest: fix whitespace issues
  deploy/examples/cluster.yaml
Labels: backport-release-1.11

#11825 Fix documentation indentation
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
Labels: skip-ci, backport-release-1.10, backport-release-1.11

#11842 monitoring: Remove alerts that don't apply to rook
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/examples/monitoring/localrules.yaml
Labels: monitoring, backport-release-1.11

#11829 mgr: revert readiness probe and go back to the original sidecar HA implementation
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  cmd/rook/ceph/ceph.go
  cmd/rook/ceph/mgr.go
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster.yaml
  deploy/examples/monitoring/service-monitor.yaml
  pkg/apis/ceph.rook.io/v1/resources.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mgr/dashboard.go
  pkg/operator/ceph/cluster/mgr/dashboard_test.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mgr/spec.go
  pkg/operator/ceph/cluster/mgr/spec_test.go
  pkg/operator/ceph/controller/spec.go
  pkg/operator/ceph/controller/spec_test.go
  pkg/operator/k8sutil/deployment.go
  pkg/operator/k8sutil/pod.go
Labels: backport-release-1.11

#11848 core: Add env var to exporter for ceph config
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
Labels: backport-release-1.11

#11852 docs: Reset the pending release notes for v1.12
  PendingReleaseNotes.md
Labels: skip-ci

#11749 Implement OSD encryption key rotation
  .github/workflows/canary-integration-test.yml
  Documentation/Storage-Configuration/Advanced/key-management-system.md
  cmd/rook/secret.go
  deploy/charts/library/templates/_cluster-role.tpl
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/common-second-cluster.yaml
  deploy/examples/common.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/keys.go
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/osd/encryption.go
  pkg/daemon/ceph/osd/encryption_test.go
  pkg/daemon/ceph/osd/key_rotation.go
  pkg/daemon/ceph/osd/kms/k8s.go
  pkg/daemon/ceph/osd/kms/kms.go
  pkg/operator/ceph/cluster/osd/config.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/key_rotation_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/k8sutil/deployment.go
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.11

#11814 docs: Clarify device class use on all pools
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  deploy/examples/pool.yaml
Labels: skip-ci, backport-release-1.11

#11866 core: add missing labels in exporter deployment
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: backport-release-1.11, ceph-exporter

#11872 ci: increase wait time for external cluster to be ready
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.11

#11864 core: add fsid to the additionalPrinterColumns on cephcluster custom resource
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.11

#11859 csi: Update port to 3300 if msgr2 is required
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.11

#11777 nfs: network mode can be set separately for cephcluster and nfs
  Documentation/CRDs/ceph-nfs-crd.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/nfs.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/nfs/spec.go
Labels: backport-release-1.11

#11903 ci: update github token in auto-assign bot
  .github/workflows/auto-assign.yaml
Labels: backport-release-1.11

#11823 osd: validate and remove duplicate topology
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/topology/topology.go
  pkg/operator/ceph/cluster/osd/topology/topology_test.go
Labels: backport-release-1.11

#11898 docs: add script to help evaluate environments for multus
  tests/scripts/multus-test.sh
Labels: skip-ci

#11919 external: pool and metadata ec pools were reversed in scripts
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.11

#11908 rgw: enableRGWDashboard can be configured by custom
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/object.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/rgw.go
Labels: backport-release-1.11

#11928 operator: use msgr2 if compression is enabled
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/config/monstore.go
Labels: backport-release-1.11

#11950 core: remove ceph-conf-dir volume mount from exporter
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: backport-release-1.11, ceph-exporter

#11320 docs: design doc for LDAP intergration with RGW
  design/ceph/object/store.md
Labels: docs, skip-ci

#11966 osd: handle global or node-local device class configuration correctly
  pkg/daemon/ceph/osd/daemon.go
  pkg/daemon/ceph/osd/device.go
  pkg/daemon/ceph/osd/device_test.go
  pkg/util/sys/device_test.go
Labels: ceph-osd, backport-release-1.10, backport-release-1.11

#11993 core: fix config format for msgr2 ipv6 monitors
  pkg/daemon/ceph/client/config.go
Labels: backport-release-1.11

#12006 build: update vault to 1.13.1
  go.mod
  go.sum
Labels: backport-release-1.11

#11947 external: make rgw call separate from cephfs and rbd
  .github/workflows/canary-integration-test.yml
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.11

#11975 object: check obc provisioner for bucket notification
  pkg/operator/ceph/object/notification/controller_test.go
  pkg/operator/ceph/object/notification/obc_label_controller.go
  pkg/operator/ceph/object/notification/obc_label_controller_test.go
Labels: backport-release-1.11
