Repository rook/rook, pull requests merged in 2024-12, with the labels that each got.

#15080 core: Fix Annotations.Merge to prevent side effects
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/annotations_test.go
Labels: backport-release-1.15, backport-release-1.16

#15066 osd: fix device class label on osd pod
  pkg/daemon/ceph/osd/device.go
  pkg/daemon/ceph/osd/volume.go
  pkg/operator/ceph/cluster/osd/key_rotation.go
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/util/sys/device.go
  pkg/util/sys/device_test.go
Labels: backport-release-1.15, backport-release-1.16

#14776 migrate OSDs to enable encryption as day-2 operation
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Advanced/ceph-osd-mgmt.md
  PendingReleaseNotes.md
  cmd/rook/ceph/osd.go
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  design/ceph/osd-migration.md
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/osd/agent.go
  pkg/daemon/ceph/osd/remove.go
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/migrate.go
  pkg/operator/ceph/cluster/osd/migrate_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/provision_spec.go
  pkg/operator/ceph/cluster/osd/replace.go
  pkg/operator/ceph/cluster/osd/replace_test.go
Labels: backport-release-1.16

#15056 file: Add support for named MDS metadata pool names
  Documentation/CRDs/Shared-Filesystem/ceph-filesystem-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/disruption/clusterdisruption/pools.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
Labels: backport-release-1.15, backport-release-1.16

#15105 docs: update guides and examples for v1.16 release
  Documentation/Upgrade/ceph-upgrade.md
  Documentation/Upgrade/rook-upgrade.md
  deploy/examples/filesystem-ec.yaml
  deploy/examples/filesystem.yaml
  deploy/examples/object-a.yaml
  deploy/examples/object-b.yaml
  deploy/examples/object-openshift.yaml
  deploy/examples/object.yaml
Labels: backport-release-1.16

#15035 Revert "object: create cosi user for each object store"
  Documentation/Storage-Configuration/Object-Storage-RGW/cosi.md
  deploy/examples/cosi/cephcosidriver.yaml
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/user.go
  pkg/operator/ceph/object/user/controller.go
  tests/integration/ceph_cosi_test.go
Labels: backport-release-1.15, backport-release-1.16

#15086 block-storage.md: Add formatting to namespaces
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Labels: backport-release-1.16

#15064 Add rgw_enable_apis option to ObjectStore CRD
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/object-multi-instance-test.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/rgw-probe.sh
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.16

#15130 ci: Remove obsolete test check from mergify
  .mergify.yml
Labels: skip-ci

#15136 ci: Add Artem to the reviewers list
  CODE-OWNERS
Labels: skip-ci

#15137 ci: Suppress the error from creating the dashboard admin user
  tests/integration/ceph_base_object_test.go
Labels: backport-release-1.16

#15139 ci: Use images from ceph-ci instead of daemon-base
  .github/workflows/daily-nightly-jobs.yml
  tests/framework/installer/ceph_installer.go
Labels: backport-release-1.15, backport-release-1.16

#15131 manifest: Update default ceph version to v19
  .github/workflows/canary-integration-suite.yml
  .github/workflows/canary-integration-test.yml
  .github/workflows/daily-nightly-jobs.yml
  .mergify.yml
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-multus-test.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc-minikube.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/examples/toolbox.yaml
  design/ceph/ceph-cluster-cleanup.md
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: backport-release-1.16

#15145 ci: Use correct ceph-ci repo
  .github/workflows/daily-nightly-jobs.yml
  tests/framework/installer/ceph_installer.go
Labels: skip-ci, backport-release-1.16

#15155 build: Add support for K8s 1.32
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  PendingReleaseNotes.md
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.16

#15138 object: add bucketPolicy to obc
  PendingReleaseNotes.md
  pkg/operator/ceph/object/bucket/provisioner.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/notification/provisioner.go
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/s3-handlers_test.go
  tests/framework/clients/bucket.go
  tests/integration/ceph_bucket_notification_test.go
  tests/integration/ceph_object_test.go
Labels: backport-release-1.16

#15158 docs: Fix misleading example for urlPrefix
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-swift.md
Labels: backport-release-1.15, backport-release-1.16

#15115 build: Update api gomod dependencies
  .github/workflows/build.yml
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/codegen.yml
  .github/workflows/crds-gen.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/docs-check.yml
  .github/workflows/golangci-lint.yaml
  .github/workflows/integration-test-config-latest-k8s/action.yaml
  .github/workflows/mod-check.yml
  .github/workflows/multus.yaml
  .github/workflows/push-build.yaml
  .github/workflows/rbac-gen.yaml
  .github/workflows/unit-test.yml
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/csi/cluster_config_test.go
Labels: dependencies, go, backport-release-1.16

#15119 doc: design ceph config passthru for object store
  design/ceph/object/store.md
Labels: skip-ci

#15160 object: allow overriding rgw configs and flags
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/config.go
  pkg/operator/ceph/object/config_test.go
  pkg/operator/ceph/object/rgw_test.go
  pkg/operator/ceph/object/spec.go
  pkg/operator/ceph/object/spec_test.go
Labels: backport-release-1.16

#15153 rgw: bulk data pool by default
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/object-ec.yaml
  deploy/examples/object-multisite-pull-realm.yaml
  deploy/examples/object-multisite.yaml
  deploy/examples/object-openshift.yaml
  deploy/examples/object.yaml
Labels: backport-release-1.16

#15178 ceph: Update s5cmd to resolve vulnerabilities
  .github/workflows/canary-integration-test.yml
  images/ceph/Makefile
Labels: backport-release-1.15, backport-release-1.16

#15185 test: fix flaky object config unit test
  pkg/operator/ceph/object/config_test.go
Labels: backport-release-1.16

#15176 doc: add object advanced config and vol mount example
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: skip-ci, backport-release-1.16

#15209 mgr: fix label selector when updating mgr active label
  pkg/operator/ceph/cluster/mgr/mgr.go
Labels: backport-release-1.15, backport-release-1.16

#15215 tests: Canary tests to wait for first mon to start
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.16
