Repository rook/rook, pull requests merged in 2024-02, with the labels that each got.

#13653 exporter: Don't delete exporter service on daemon deletion
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: backport-release-1.12, backport-release-1.13

#13663 csi: Fix NetNamespaceFilePath generation with namespace instead of name
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: bug, backport-release-1.13

#13670 ci: check for gofmt usage in golangci-lint
  .github/workflows/golangci-lint.yaml
Labels: backport-release-1.13

#13652 core: Skip reconcile if override configmap is empty
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/controller/predicate_test.go
Labels: backport-release-1.13

#13675 ci: disk in github action increased to 75G from 64G
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/rgw-multisite-test/action.yml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.12, backport-release-1.13

#13694 ci: fix detection of GH actions extra disk
  .github/workflows/canary-integration-test.yml
  .github/workflows/daily-nightly-jobs.yml
  .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .github/workflows/rgw-multisite-test/action.yml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.12, backport-release-1.13

#13697 ci: remove `/dev` prefix from the `TEST_SCRATCH_DEVICE` and `deviceFilter` spec.
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.12, backport-release-1.13

#13699 test: use mounter kernal instead of fuse
  tests/framework/installer/ceph_manifests.go
Labels: backport-release-1.12, backport-release-1.13

#13511 core: set blocking PDB even if no unhealthy PGs appear
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
Labels: backport-release-1.13

#13673 osd: correct counting the devices when metadataDevice is set
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: ceph-osd, backport-release-1.13

#13405 helm: allow defining multiple cephEcStorageClass
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: helm

#13720 docs: fix CephCluster.spec.cephVersion.imagePullPolicy list item
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
Labels: docs, backport-release-1.13

#13728 core: remove ownerRef from networkFence
  pkg/operator/ceph/cluster/watcher.go
Labels: backport-release-1.12, backport-release-1.13

#13665 csi: remove CSI_ENABLE_READ_AFFINITY
  Documentation/Helm-Charts/operator-chart.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin.yaml
Labels: backport-release-1.13

#13693 Disallow legacy hostNetwork together with non-default provider
  .commitlintrc.json
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/network.go
  pkg/apis/ceph.rook.io/v1/network_test.go
  pkg/apis/ceph.rook.io/v1/types.go
Labels: bug, backport-release-1.13

#13741 mgr: remove privileged security context from mgr sidecar container
  pkg/operator/ceph/cluster/mgr/spec.go
Labels: backport-release-1.13

#13718 core: Delete networkFence CRs during cluster removal
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/csi/csi.go
Labels: backport-release-1.13

#13768 core: Continue processing PVs for network fencing when no node IPs found
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: backport-release-1.13

#13758 docs: Update roadmap for the 1.14 release
  ROADMAP.md
Labels: skip-ci

#13784 ci: stop nightly canary from running in forks
  .github/workflows/daily-nightly-jobs.yml
Labels: skip-ci

#13772 pool: Skip crush rule update when not needed
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
Labels: backport-release-1.13

#13794 mon: set mon pdb max unavailable as 2 in case of 5 or more mons.
  pkg/operator/ceph/cluster/mon/drain.go
  pkg/operator/ceph/cluster/mon/drain_test.go
Labels: backport-release-1.13

#13801 csi: disable cephFs network Fencing temporarily
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
Labels: backport-release-1.13

#13809 doc: PendingReleaseNotes for update netNamespaceFilePath PR
  PendingReleaseNotes.md
Labels: skip-ci

#13833 doc: fix broken links
  Documentation/README.md
Labels: docs, backport-release-1.13
