Repository rook/rook, pull requests merged in 2024-03, with the labels that each got.

#13641 build: add ability to stash docker build context
  images/ceph/Makefile
Labels: stale

#13836 csi: update CSIDriverOption params during saving cluster config
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
Labels: backport-release-1.13

#13865 build: use 'baseos' as repo for iproute install
  images/ceph/Dockerfile
Labels: backport-release-1.12, backport-release-1.13

#13870 docs: separate network providers into sub-doc
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/network-providers.md
Labels: skip-ci

#13877 build: fix master version helm values replacement
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: build, helm, backport-release-1.13

#13845 doc: fix broken links
  Documentation/.pages
  Documentation/Getting-Started/.pages
  Documentation/Getting-Started/intro.md
  Documentation/README.md
  Documentation/intro.md
  mkdocs.yml
Labels: backport-release-1.13

#13885 doc: remove legacy rgw service documentation
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: docs, skip-ci, backport-release-1.13

#13875 doc: update objectuser example in the external install
  Documentation/CRDs/Cluster/external-cluster.md
Labels: docs

#13893 ci: Remove minor version from setup-go in govulncheck
  .github/workflows/golangci-lint.yaml
Labels: backport-release-1.13

#13858 doc: add steps to configure external mode with admin privileges
  Documentation/CRDs/Cluster/external-cluster.md
Labels: docs, skip-ci

#13913 core: Set default ceph version to v18.2.2
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  deploy/examples/toolbox.yaml
  design/ceph/ceph-cluster-cleanup.md
  images/ceph/Makefile
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: backport-release-1.13

#13902 exporter: applying labels from monitoring section to ceph-exporter
  deploy/examples/cluster.yaml
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
Labels: backport-release-1.13

#13931 helm: use toYaml for discovery nodeAffinity
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.13

#13761 mgr: enable rook orchestrator mgr module by default
  deploy/examples/cluster-on-pvc-minikube.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/common-second-cluster.yaml
Labels: debug-ci

#13830 osd: fix removing key file timing
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.13

#13738 build: add support for go 1.22
  .github/workflows/build.yml
  Makefile
  build/makelib/golang.mk
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
Labels: backport-release-1.13

#13982 external: fix v2 port check in external script
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.13

#13986 build: Add 1.14 branch to the mergify backports
  .mergify.yml
Labels: skip-ci

#13991 object: Set non-ec shared pool to metadata pool
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
Labels: backport-release-1.14

#13993 ci: Fix mergify auto merge test names
  .github/workflows/canary-integration-test.yml
  .mergify.yml
Labels: skip-ci
