Repository rook/rook, pull requests merged in 2024-04, with the labels that each got.

#14005 core: use correct pool name to disable mirroring
  pkg/operator/ceph/pool/controller.go
Labels: backport-release-1.14

#13997 doc: update release notes and upgrade docs for v1.14
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
Labels: docs, skip-ci, backport-release-1.14

#13958 operator: improve the output of kubectl get
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/status.go
  pkg/operator/ceph/pool/status_test.go
Labels: backport-release-1.14

#14019 rgw: fix typo on crd endpoint address
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.14

#14014 helm: Separate repository and tags for csi images in the operator chart
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.14

#14027 ci: update go version in govulncheck
  .github/workflows/golangci-lint.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: backport-release-1.13, backport-release-1.14

#14023 doc: make CSI host netowrking required
  Documentation/CRDs/Cluster/network-providers.md
  Documentation/Upgrade/rook-upgrade.md
Labels: docs, skip-ci, backport-release-1.14

#14033 doc: Reset pending release notes
  PendingReleaseNotes.md
Labels: skip-ci

#14046 doc: fix network provider bullets and numbering
  Documentation/CRDs/Cluster/network-providers.md
Labels: docs, skip-ci, backport-release-1.14

#14036 subvolumegroup: add support for size and datapool
  Documentation/CRDs/Shared-Filesystem/ceph-fs-subvolumegroup-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/subvolumegroup.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  tests/framework/installer/ceph_manifests.go
Labels: backport-release-1.14

#14002 osd: Prevent osd reconcile when device set names duplicated
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
Labels: backport-release-1.13, backport-release-1.14

#14052 Cleanup RADOS namespace with forced deletion annotation
  Documentation/Storage-Configuration/ceph-teardown.md
  cmd/rook/ceph/cleanup.go
  pkg/daemon/ceph/cleanup/radosnamespace.go
  pkg/daemon/ceph/cleanup/radosnamespace_test.go
  pkg/daemon/ceph/client/image.go
  pkg/daemon/ceph/client/image_test.go
  pkg/operator/ceph/controller/cleanup.go
  pkg/operator/ceph/controller/cleanup_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  tests/framework/clients/block.go
Labels: backport-release-1.14

#14049 operator: make CephBlockPoolRadosNamespace and CephFilesystemSubVolumeGroup get outputs more verbose
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/subvolumegroup.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
Labels: backport-release-1.14

#14079 operator: load cluster owner info in LoadClusterInfo
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
Labels: backport-release-1.14

#14089 csi: only create CSI config configmap in CSI reconciler
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/csi/cluster_config.go
  pkg/operator/ceph/csi/cluster_config_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/k8sutil/resources.go
Labels: backport-release-1.14

#14088 helm: Use correct metadata and data ec block pool
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
Labels: backport-release-1.14

#14096 ci: Update mergify rules for K8s 1.30
  .mergify.yml
Labels: skip-ci

#14100 osd: Legacy LVM-based OSDs on PVCs crash on resize init container
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: backport-release-1.12, backport-release-1.13, backport-release-1.14

#14107 doc: fix external cluster document
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
Labels: skip-ci, backport-release-1.14

#14119 fixing typo in ceph-object-store-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: skip-ci, backport-release-1.14

#14083 csi: remove out-dated prerequisites
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-clone.md
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
Labels: docs

#14129 csi: update csi sidecars image version
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  tests/framework/utils/snapshot.go
Labels: csi, backport-release-1.14

#14106 mon: fix mon scaledown when mons are portable
  pkg/operator/ceph/cluster/mon/health.go
Labels: backport-release-1.14
