Repository rook/rook, pull requests merged in 2024-08, with the labels that each got.

#14517 csi: explicitly set Topology feature-gate
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: backport-release-1.15

#14532 object: use advertise endpoint for admin ops
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  design/ceph/object/store.md
  pkg/operator/ceph/object/admin.go
  pkg/operator/ceph/object/admin_test.go
Labels: backport-release-1.15

#14542 csi: add pvc & pod yamls for block volume mode
  deploy/examples/csi/rbd/raw-block-pod.yaml
  deploy/examples/csi/rbd/raw-block-pvc.yaml
Labels: backport-release-1.15

#14546 docs: fix affinity docs in operator chart
  Documentation/Helm-Charts/operator-chart.gotmpl.md
  Documentation/Helm-Charts/operator-chart.md
Labels: backport-release-1.15

#14559 docs: update upgrade docs for v1.15
  Documentation/Upgrade/ceph-upgrade.md
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
Labels: backport-release-1.15

#14566 core: Support k8s versions 1.26 through 1.31
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  PendingReleaseNotes.md
Labels: backport-release-1.15

#14565 ci: fix failing multus validation tool test
  .github/workflows/multus.yaml
  tests/scripts/multus/host-cfg-ds.yaml
Labels: backport-release-1.14, backport-release-1.15

#14579 csi: update csi-addons to v0.9.0
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/controller_test.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/cluster/watcher_test.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
  tests/scripts/csiaddons.sh
Labels: backport-release-1.15

#14576 core: Add annotations and labels to detect version jobs
  Documentation/CRDs/specification.md
  deploy/examples/cluster.yaml
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/annotations_test.go
  pkg/apis/ceph.rook.io/v1/keys.go
  pkg/apis/ceph.rook.io/v1/labels.go
  pkg/apis/ceph.rook.io/v1/labels_test.go
  pkg/operator/ceph/controller/network.go
  pkg/operator/ceph/controller/version.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.14, backport-release-1.15

#14597 build: Update codegen deepcopy for swift
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
Labels: backport-release-1.15

#14586 csi: storageclass update to gp2-csi
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/Contributing/rook-test-framework.md
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  pkg/operator/ceph/cluster/osd/create_test.go
Labels: backport-release-1.15

#14599 csi: update csi-operator to use latest tag v0.1
  Documentation/CRDs/specification.md
  Makefile
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  deploy/examples/csi-operator.yaml
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
  pkg/operator/ceph/cluster/mgr/dashboard_test.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/k8sutil/customresource.go
Labels: backport-release-1.15

#14604 test: fix 'make test' on arm mac
  build/makelib/golang.mk
Labels: backport-release-1.15

#14550 manifest: add registry name to docker images
  Documentation/Helm-Charts/operator-chart.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/direct-mount.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  deploy/examples/osd-purge.yaml
  deploy/examples/sqlitevfs-client.yaml
  deploy/examples/toolbox-job.yaml
  deploy/examples/toolbox-operator-image.yaml
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.15

#14598 core: add configuration option for metrics bindAddress
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/cr_manager.go
Labels: backport-release-1.14, backport-release-1.15

#14435 osd: reweight osd while resizing
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-test.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/osd.go
  pkg/daemon/ceph/client/osd_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
Labels: backport-release-1.15

#14618 csi: use specific tag instead of latest image
  deploy/examples/csi-operator.yaml
Labels: backport-release-1.15

#14627 external: remove the false bool values from config file
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.15

#14629 multus: fix default service account handling
  cmd/rook/userfacing/multus/validation/validation.go
  tests/scripts/multus/test-110-cli.sh
  tests/scripts/multus/test-210-stretch-overlap.sh
  tests/scripts/multus/test-220-stretch-pub-and-cluster.sh
  tests/scripts/multus/test-230-stretch-pub-only.sh
  tests/scripts/multus/test-240-stretch-cluster-only.sh
Labels: backport-release-1.14, backport-release-1.15

#14631 core: fix host cleanup jobs to read flags correctly.
  cmd/rook/ceph/cleanup.go
Labels: backport-release-1.14, backport-release-1.15

#14636 core: fix Ceph monitor deployment in separate zones
  pkg/operator/ceph/cluster/mon/spec.go
  pkg/operator/ceph/cluster/mon/spec_test.go
Labels: backport-release-1.14, backport-release-1.15

#14630 tests: fix unit test failure on macOS due to temp directory path
  pkg/operator/ceph/csi/peermap/config_test.go
Labels: backport-release-1.15

#14641 docs: fix ceph object multisite and update source code layout
  Documentation/Contributing/development-flow.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-multisite.md
Labels: backport-release-1.15

#14660 docs: Reset pending release notes
  PendingReleaseNotes.md
Labels: skip-ci

#14652 docs: exhaustively list all priority class options
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
Labels: backport-release-1.15

#14642 helm: reorder volumes in rook-ceph-csi scc for argocd diff to show no changes
  deploy/charts/rook-ceph/templates/securityContextConstraints.yaml
  deploy/examples/operator-openshift.yaml
Labels: backport-release-1.14, backport-release-1.15
