Repository rook/rook, pull requests merged in 2024-10, with the labels that each got.

#14782 csi: add sc privileged to logrotate sidecar container
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/csi-logrotate-sidecar.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-holder.yaml
  pkg/operator/ceph/csi/template/nfs/csi-nfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-holder.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: backport-release-1.15

#14801 rgw: fix CephObjectZone failing with pre-existing pools
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.15

#14798 mds: fix liveness probe timeout
  pkg/operator/ceph/file/mds/livenessprobe.go
  pkg/operator/ceph/file/mds/livenessprobe.sh
Labels: ceph-mds, backport-release-1.14, backport-release-1.15

#14800 test: do not always run `sudo lsblk` in github-action-helper.sh
  tests/scripts/github-action-helper.sh
Labels: test

#14805 mon: Do not remove extra mon in middle of failover
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: backport-release-1.15

#14719 doc: osd migration design
  design/ceph/osd-migration.md
Labels: docs, skip-ci

#14820 multus: do not force delete in validation cleanup
  pkg/daemon/multus/resources.go
Labels: backport-release-1.15

#14831 csi: disable fencing in Rook
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
  Documentation/Troubleshooting/ceph-csi-common-issues.md
  pkg/operator/ceph/cluster/watcher.go
Labels: backport-release-1.14, backport-release-1.15

#14842 test: improve reliability of canary rgw-multisite-testing
  .github/workflows/canary-integration-test.yml
  .github/workflows/rgw-multisite-test/action.yml
  tests/scripts/github-action-helper.sh
Labels: test

#14854 core: Skip counting exporter pods as a ceph pod
  pkg/operator/ceph/cluster/nodedaemon/add.go
Labels: backport-release-1.15

#14862 core: fix deletion of the osd-replace-config cm
  pkg/operator/ceph/cluster/osd/osd.go
Labels: backport-release-1.15

#14870 ci: macos-12 will EOL soon, let's use latest tag
  .github/workflows/build.yml
Labels: backport-release-1.15

#14872 test: fix ceph image tag used by most canary tests
  .github/workflows/canary-integration-test.yml
  tests/scripts/github-action-helper.sh
Labels: test

#14875 csi: fix typo in image version
  deploy/examples/operator.yaml
Labels: backport-release-1.15

#14886 ci: remove incorrect comment from codegen workflow
  .github/workflows/codegen.yml
Labels: backport-release-1.15

#14891 Revert "docs: add documentation for rbd volumegroupsnapshot"
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/pvc.yaml
  deploy/examples/csi/rbd/groupsnapshot.yaml
  deploy/examples/csi/rbd/groupsnapshotclass.yaml
  deploy/examples/csi/rbd/pvc.yaml
Labels: docs, backport-release-1.15

#14901 osd: mount /run/udev in the init container for ceph-volume activate
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
Labels: backport-release-1.14, backport-release-1.15

#14835 object: also use system certs for validating RGW cert
  Documentation/CRDs/Cluster/external-cluster/provider-export.md
  deploy/examples/create-external-cluster-resources.py
  pkg/operator/ceph/object/s3-handlers.go
  pkg/operator/ceph/object/s3-handlers_test.go
Labels: backport-release-1.14, backport-release-1.15

#14910 test: specify ceph image correctly
  .github/workflows/canary-integration-test.yml
  .github/workflows/encryption-pvc-kms-ibm-kp/action.yml
Labels: backport-release-1.15

#14928 docs: fix external doc broken links
  Documentation/CRDs/Cluster/external-cluster/advance-external.md
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/Cluster/external-cluster/upgrade-external.md
Labels: backport-release-1.15

#14934 test: make debug-ci label work again
  .github/workflows/canary-integration-test.yml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/multus.yaml
  .github/workflows/tmate_debug/action.yml
Labels: backport-release-1.14, backport-release-1.15

#14942 csi: Remove version check for k8s and cephcsi
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/version.go
  pkg/operator/ceph/csi/version_test.go
Labels: backport-release-1.15

#14944 doc: avoid always enabling tmate session
  .github/workflows/tmate_debug/action.yml
Labels: backport-release-1.14, backport-release-1.15

#14936 doc: clarify dataDirHostPath must be unique for each cluster
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/Storage-Configuration/ceph-teardown.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc-minikube.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
Labels: backport-release-1.15
