Repository rook/rook, pull requests merged in 2024-06, with the labels that each got.

#14299 build: remove iproute build dependency on centos repo
  images/ceph/Dockerfile
Labels: backport-release-1.14

#14302 multus: add and test ipv6 support for validation tool
  pkg/daemon/multus/nginx-config.yaml
  pkg/daemon/multus/templates.go
  tests/scripts/multus/default-public-cluster-nads.yaml
Labels: backport-release-1.14

#14229 doc: Update the roadmap for 1.15
  ROADMAP.md
Labels: skip-ci

#13500 mon: Allow overriding the mon endpoint with annotation
  Documentation/CRDs/Cluster/network-providers.md
  pkg/operator/ceph/cluster/mon/node.go
  pkg/operator/ceph/cluster/mon/node_test.go
Labels: backport-release-1.14

#14313 monitoring: fix exporter service monitor selector
  deploy/examples/monitoring/exporter-service-monitor.yaml
Labels: backport-release-1.14

#14312 monitoring: update to the latest ceph prometheus rules
  deploy/charts/rook-ceph-cluster/prometheus/localrules.yaml
  deploy/examples/monitoring/localrules.yaml
Labels: backport-release-1.14

#14323 helm: allow custom labels and annotations for storage classes
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  deploy/charts/rook-ceph-cluster/templates/cephblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
  deploy/charts/rook-ceph-cluster/templates/cephfilesystem.yaml
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.14

#14325 pool: get the exact deviceClass name instead of crushroot+deviceClass
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/pool_test.go
Labels: backport-release-1.14

#13876 doc: add recommendation for nfs in external cluster
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/Storage-Configuration/NFS/nfs-csi-driver.md
Labels: docs, skip-ci, backport-release-1.14

#14339 monitoring: Set honor labels on the service monitor
  deploy/examples/monitoring/service-monitor.yaml
  pkg/operator/k8sutil/prometheus.go
Labels: backport-release-1.14

#14362 core: revert increase storage deviceset name limit to 50
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
Labels: backport-release-1.14

#14374 osd: fix activate failure when block device moves
  pkg/operator/ceph/cluster/osd/spec.go
Labels: backport-release-1.13, backport-release-1.14

#14353 external: add support for config file in external mode
  .github/workflows/canary-integration-test.yml
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  deploy/examples/create-external-cluster-resources.py
  images/ceph/Makefile
  tests/external-cluster/ceph-status-out
  tests/external-cluster/external-config.ini
Labels: backport-release-1.14

#14342 docs(fix): missing ** in filesystem-storage.md
  Documentation/Storage-Configuration/Shared-Filesystem-CephFS/filesystem-storage.md
Labels: backport-release-1.14
