Repository rook/rook, pull requests merged in 2024-09, with the labels that each got.

#14645 osd: discover metadata and wal devices for raw device cleanup
  pkg/daemon/ceph/cleanup/disk.go
  pkg/daemon/ceph/osd/volume.go
Labels: backport-release-1.15

#14667 mon: Remove extra mon from quorum before taking down pod
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: backport-release-1.15

#14694 csi: update to new cephcsi release
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: backport-release-1.15

#14653 core: check for duplicate ceph fs pool names
  pkg/operator/ceph/file/filesystem.go
  pkg/operator/ceph/file/filesystem_test.go
Labels: backport-release-1.15

#14693 csi: stop deleting csi-operator resources
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.15

#14709 pool: Allow negative step num in crush rule
  pkg/daemon/ceph/client/crush.go
  pkg/daemon/ceph/client/crush_rule.go
  pkg/daemon/ceph/client/crush_rule_test.go
Labels: backport-release-1.15

#14702 doc: add the pv encryption key rotation job
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
Labels: skip-ci

#14720 docs: Add documentation for VolumeGroupSnapshot
  Documentation/Storage-Configuration/Ceph-CSI/.pages
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-snapshot.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/examples/csi/cephfs/groupsnapshot.yaml
  deploy/examples/csi/cephfs/groupsnapshotclass.yaml
  deploy/examples/csi/cephfs/pvc.yaml
Labels: backport-release-1.15

#14717 Configure prio-limit for ceph exporter container
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/cluster.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/cluster/nodedaemon/exporter.go
  pkg/operator/ceph/cluster/nodedaemon/exporter_test.go
Labels: backport-release-1.15

#14731 core: Enable annotations on crash collector
  pkg/apis/ceph.rook.io/v1/annotations.go
  pkg/apis/ceph.rook.io/v1/annotations_test.go
  pkg/operator/ceph/cluster/nodedaemon/crash.go
Labels: backport-release-1.14, backport-release-1.15

#14722 external: mds caps to healthchecker/cephfs users
  deploy/examples/create-external-cluster-resources.py
Labels: backport-release-1.15

#14718 docs: update external docs with a better structure
  Documentation/CRDs/Cluster/external-cluster/.pages
  Documentation/CRDs/Cluster/external-cluster/advance-external.md
  Documentation/CRDs/Cluster/external-cluster/consumer-import.md
  Documentation/CRDs/Cluster/external-cluster/external-cluster.md
  Documentation/CRDs/Cluster/external-cluster/provider-export.md
  Documentation/CRDs/Cluster/external-cluster/upgrade-external.md
Labels: skip-ci, backport-release-1.15

#14746 csi: fix the ROOK_CSI_DISABLE_DRIVER flag in the csi reconcile
  pkg/operator/ceph/csi/controller.go
Labels: backport-release-1.15
