Repository rook/rook, pull requests merged in 2025-06, with the labels that each got.

#15934 nfs: use tabs instead of spaces in nfs rgw config
  pkg/operator/ceph/nfs/config.go
Labels: backport-release-1.17

#15961 doc: improve documentation around object store certificates
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: backport-release-1.17

#15972 osd: wipe encryted osd disk from other cluster
  pkg/daemon/ceph/osd/volume.go
  pkg/daemon/ceph/osd/volume_test.go
Labels: backport-release-1.17

#16002 ci: don't use helm.sh up and remove helm.sh
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/Contributing/rook-test-framework.md
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/environment.go
  tests/integration/ceph_base_keystone_test.go
  tests/scripts/helm.sh
Labels: helm, ci

#16005 osd: update the table of allowed configutations
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
Labels: bug, docs, does not block release, skip-ci, backport-release-1.17

#16038 object: allow deletion of CephObjectStoreUser even if secret is missing
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.17

#16050 csi: update csi version to 3.14.1
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: backport-release-1.17

#16055 helm: support the six most recent helm versions
  .github/workflows/integration-test-helm-suite.yaml
  Documentation/Helm-Charts/ceph-cluster-chart.gotmpl.md
  Documentation/Helm-Charts/ceph-cluster-chart.md
  Documentation/Helm-Charts/operator-chart.gotmpl.md
  Documentation/Helm-Charts/operator-chart.md
  PendingReleaseNotes.md
Labels: helm

#16061 csi: Provide a flag to skip csi user creation
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
Labels: backport-release-1.17
