Repository rook/rook, pull requests merged in 2025-09, with the labels that each got.

#16375 docs: fix `authKeystone` usage in Object Storage CRD docs
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
Labels: backport-release-1.18

#16409 osd: rotate lockbox keys for encrypted osd
  pkg/operator/ceph/cluster/osd/labels.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/update.go
Labels: cephx-rotation, backport-release-1.18

#16372 core: delete bootstrap keys
  pkg/operator/ceph/cluster/cluster.go
Labels: cephx-rotation, backport-release-1.18

#16452 csi: fix prior cephx key deletion logic
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
Labels: cephx-rotation, backport-release-1.18

#16457 helm: refactoring of rook-ceph's configmap to be easier to read and maintain
  deploy/charts/rook-ceph/templates/configmap.yaml
Labels: backport-release-1.18

#16496 core: fix ObjectZoneSpec.ZoneGroup and ObjectZoneGroupSpec.Realm field descriptions
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.17, backport-release-1.18

#16506 osd: updated blocking pdbs if drained node is back
  pkg/operator/ceph/disruption/clusterdisruption/osd.go
  pkg/operator/ceph/disruption/clusterdisruption/osd_test.go
Labels: backport-release-1.18

#16521 doc: add parth arora to the maintainers list
  .github/workflows/codespell.yaml
  CODE-OWNERS
  OWNERS.md
Labels: docs, skip-ci

#16531 csi: csi-addon no longer needed for network fence
  Documentation/Storage-Configuration/Block-Storage-RBD/block-storage.md
Labels: backport-release-1.17, backport-release-1.18

#16541 core: add PHASE column to cephbn
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.18

#16543 core: add PHASE column to cephnfs
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.18

#16542 core: add PHASE column to cephor
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.18
