Repository rook/rook, pull requests merged in 2025-01, with the labels that each got.

#15037 csi: update groupsnapshot container arg
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-volume-group-snapshot.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
  deploy/examples/csi/cephfs/groupsnapshot.yaml
  deploy/examples/csi/cephfs/groupsnapshotclass.yaml
Labels: backport-release-1.16

#15235 ci: update golang.org/x/net to 0.33
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: backport-release-1.15, backport-release-1.16

#15242 osd: use bluestore if store type is empty
  pkg/operator/ceph/cluster/osd/migrate.go
Labels: backport-release-1.16

#15245 csi: Set correct driver name with csi operator
  pkg/operator/ceph/csi/operator_driver.go
  pkg/operator/ceph/operator.go
Labels: backport-release-1.16

#15243 external: fix rados namespace sc name
  deploy/examples/create-external-cluster-resources.py
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.16

#15264 csi: Set driver name to same as the operator namespace
  pkg/operator/ceph/csi/operator_driver.go
Labels: backport-release-1.16

#15269 docs: Reset pending release notes
  PendingReleaseNotes.md
Labels: skip-ci

#15272 docs: Update roadmap for release 1.17
  ROADMAP.md
Labels: docs

#15276 Fix s5cmd arch
  images/ceph/Makefile
Labels: backport-release-1.15, backport-release-1.16

#15258 core: add tolerations to crashcollector pruner cronJob pod
  pkg/operator/ceph/cluster/nodedaemon/pruner.go
  pkg/operator/ceph/cluster/nodedaemon/pruner_test.go
  pkg/operator/ceph/cluster/nodedaemon/reconcile.go
Labels: backport-release-1.15, backport-release-1.16

#15270 operator: omit values from mon db config logs
  pkg/operator/ceph/config/monstore.go
Labels: backport-release-1.15, backport-release-1.16

#15288 build: Auto merge backports without blocking on multisite test
  .mergify.yml
Labels: skip-ci

#15310 ci: codespell: s/re-using/reusing/
  pkg/operator/ceph/object/objectstore.go
  tests/scripts/multus/host-cfg-ds.yaml
Labels: backport-release-1.16
