Repository rook/rook, pull requests merged in 2025-04, with the labels that each got.

#15622 tests: fix intermittent failure of TestWaitForDeploymentsToUpdate
  pkg/operator/k8sutil/deployment_test.go
Labels: backport-release-1.16, backport-release-1.17

#15554 rgw: Support Kafka auth mechanism parameter
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/bucket-topic.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/topic_test.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/topic/provisioner.go
  pkg/operator/ceph/object/topic/provisioner_test.go
Labels: backport-release-1.17

#15459 rbdmirror: mirroring b/w implicit and defined ns
  Documentation/CRDs/Block-Storage/ceph-block-pool-crd.md
  Documentation/CRDs/Block-Storage/ceph-block-pool-rados-namespace-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/mirror_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
  pkg/operator/ceph/pool/validate.go
Labels: backport-release-1.17

#15624 object: updated cephobjectstore zone spec
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.17

#15359 object: add CephObjectStoreUser.spec.keys
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
  tests/integration/ceph_object_test.go
  tests/integration/object/user/userkeys/userkeys.go
Labels: backport-release-1.17

#15636 operator: decouple mon and mgr post-startup operations
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/mgr/orchestrator.go
Labels: backport-release-1.17

#15645 mon: fix mon rbac for endpoint slice
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/examples/common.yaml
Labels: backport-release-1.17

#15652 nfs: set allow_set_io_flusher_fail=true in config
  pkg/operator/ceph/nfs/config.go
Labels: backport-release-1.16, backport-release-1.17

#15653 ci: Enable automerge for 1.17 backports
  .mergify.yml
Labels: skip-ci

#15660 csi: remove dummy code in csi driver creation
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/csidriver.go
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.17

#15643 doc: update release notes and upgrade docs
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
Labels: skip-ci, backport-release-1.17

#15669 helm: Allow specifying an ingress object store port to override default
  deploy/charts/rook-ceph-cluster/templates/_helpers.tpl
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-ingress.yaml
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.16, backport-release-1.17

#15677 rbdmirror: fix the rados namespace health checkup
  pkg/daemon/ceph/client/mirror_health.go
Labels: backport-release-1.16, backport-release-1.17

#15648 ci: fix rgw flaky ci test
  .github/workflows/canary-integration-test.yml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.17

#15641 core: Reconcile CRs only after the finalizer is added by Rook
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/predicate.go
  pkg/operator/ceph/controller/finalizer.go
  pkg/operator/ceph/controller/finalizer_test.go
  pkg/operator/ceph/controller/predicate.go
  pkg/operator/ceph/file/controller.go
  pkg/operator/ceph/file/controller_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/file/subvolumegroup/controller_test.go
  pkg/operator/ceph/nfs/controller.go
  pkg/operator/ceph/nfs/controller_test.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/controller_test.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/topic/controller_test.go
  pkg/operator/ceph/object/user/controller.go
  pkg/operator/ceph/object/user/controller_test.go
  pkg/operator/ceph/object/zone/controller.go
  pkg/operator/ceph/object/zone/controller_test.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
Labels: backport-release-1.17

#15687 update oauth package Fix CVE 2025 22868
  go.mod
  go.sum
  pkg/apis/go.mod
  pkg/apis/go.sum
Labels: backport-release-1.17

#15670 ci: update minimum k8s supported version to 1.28
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  .mergify.yml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
Labels: backport-release-1.17

#15690 core: update cephstatus fsmap gid type to uint64
  pkg/daemon/ceph/client/status.go
  pkg/daemon/ceph/client/status_test.go
Labels: backport-release-1.16, backport-release-1.17

#15693 csi: update cephcsi to v3.14.0
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: csi, backport-release-1.17

#15702 docs: fix typos in CephObjectStoreUser.spec.keys example
  Documentation/Storage-Configuration/Object-Storage-RGW/object-storage.md
Labels: skip-ci, backport-release-1.17

#15705 test: update ExecuteCommandWithTimeout unit test
  pkg/util/exec/exec_test.go
Labels: backport-release-1.17

#15704 core: Set default ceph version to v19.2.2
  Documentation/CRDs/Cluster/ceph-cluster-crd.md
  Documentation/CRDs/Cluster/host-cluster.md
  Documentation/CRDs/Cluster/pvc-cluster.md
  Documentation/CRDs/Cluster/stretch-cluster.md
  Documentation/Upgrade/ceph-upgrade.md
  deploy/charts/rook-ceph-cluster/values.yaml
  deploy/examples/cluster-external-management.yaml
  deploy/examples/cluster-on-local-pvc.yaml
  deploy/examples/cluster-on-pvc.yaml
  deploy/examples/cluster-stretched-aws.yaml
  deploy/examples/cluster-stretched.yaml
  deploy/examples/cluster.yaml
  deploy/examples/images.txt
  design/ceph/ceph-cluster-cleanup.md
  images/ceph/Makefile
  tests/manifests/test-cluster-on-pvc-encrypted.yaml
Labels: backport-release-1.16, backport-release-1.17

#15686 doc: add CephBucketTopic kafka mechanism field to upgrade docs
  Documentation/Upgrade/rook-upgrade.md
  PendingReleaseNotes.md
Labels: skip-ci, backport-release-1.17

#15710 tests: Lower threshold for mon free space
  tests/framework/installer/ceph_manifests.go
Labels: backport-release-1.16, backport-release-1.17

#15718 mon: always delete mon canary pods
  pkg/operator/ceph/cluster/mon/service.go
Labels: backport-release-1.16, backport-release-1.17

#15709 osd: Document the ceph conf overrides per node
  Documentation/Storage-Configuration/Advanced/ceph-configuration.md
Labels: backport-release-1.17

#15733 ci: run selective disk cleanups in go CI tests
  .github/workflows/integration-test-config-latest-k8s/action.yaml
Labels: backport-release-1.16, backport-release-1.17

#15521 object: add CephBucketTopic .spec.endpoint.kafka.{user,password}SecretRef
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-notifications.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  go.mod
  go.sum
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/object/topic/controller.go
  pkg/operator/ceph/object/topic/controller_test.go
  pkg/operator/ceph/object/topic/provisioner.go
  pkg/operator/ceph/object/topic/provisioner_test.go
  tests/framework/installer/ceph_manifests.go
  tests/integration/ceph_object_test.go
  tests/integration/object/topic/kafka/kafka.go
  tests/integration/object/util/sns/sns.go
Labels: backport-release-1.17

#15747 object: Log all reconcile errors during object store creation
  pkg/operator/ceph/object/controller.go
Labels: backport-release-1.16, backport-release-1.17

#15758 docs: Reset pending release notes
  PendingReleaseNotes.md
Labels: skip-ci

#15759 build: Push arch specific images to the registries
  build/release/Makefile
Labels: skip-ci

#15764 object: lower retry log verbosity in notification OBC controller
  pkg/operator/ceph/object/notification/obc_label_controller.go
Labels: backport-release-1.17

#15769 doc: fix indentation and add enabled: true in dashboard config example
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
Labels: backport-release-1.17

#15750 test: update Prometheus Operator to v0.82.0
  Documentation/Storage-Configuration/Monitoring/ceph-monitoring.md
  tests/framework/installer/ceph_installer.go
  tests/scripts/auto-grow-storage.sh
  tests/scripts/create-dev-cluster.sh
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.17

#15761 osd: fix osd disk cleanup for mpath setups
  pkg/daemon/ceph/osd/remove.go
Labels: backport-release-1.16, backport-release-1.17

#15795 ci: update latest k8s version to 1.33
  .github/workflows/canary-test-config/action.yaml
  .github/workflows/integration-test-helm-suite.yaml
  .github/workflows/integration-test-keystone-auth-suite.yaml
  .github/workflows/integration-test-mgr-suite.yaml
  .github/workflows/integration-test-multi-cluster-suite.yaml
  .github/workflows/integration-test-object-suite.yaml
  .github/workflows/integration-test-smoke-suite.yaml
  .github/workflows/integration-test-upgrade-suite.yaml
  .github/workflows/integration-tests-on-release.yaml
  Documentation/Getting-Started/Prerequisites/prerequisites.md
  Documentation/Getting-Started/quickstart.md
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.17
