Repository rook/rook, pull requests merged in 2025-08, with the labels that each got.

#16029 OSD: implement automated cephx key rotation for osds
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/osd/create.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/cluster/osd/spec.go
  pkg/operator/ceph/cluster/osd/spec_test.go
  pkg/operator/ceph/cluster/osd/update.go
  pkg/operator/ceph/cluster/osd/update_test.go
Labels: cephx-rotation, backport-release-1.18

#16220 object: fix bucket policy in sync detection
  pkg/operator/ceph/object/bucket/provisioner.go
Labels: backport-release-1.17, backport-release-1.18

#16223 object: simplify obc storageclass lookup
  pkg/operator/ceph/object/bucket/api-handlers.go
  pkg/operator/ceph/object/bucket/provisioner.go
Labels: backport-release-1.18

#16224 test: factor out util/admin package for setup of ceph admin client
  tests/integration/object/bucketowner/bucketowner.go
  tests/integration/object/user/userkeys/userkeys.go
  tests/integration/object/util/admin/admin.go
  tests/integration/object/util/s3/s3.go
  tests/integration/object/util/sns/sns.go
Labels: backport-release-1.18

#16257 tests: Upgrade from 1.17 to master
  tests/framework/installer/ceph_installer.go
  tests/framework/installer/ceph_manifests.go
  tests/framework/installer/ceph_manifests_previous.go
  tests/integration/ceph_upgrade_test.go
Labels: backport-release-1.18

#16244 csi: add CrossNamespaceVolumeDataSource feature gate
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/clusterrole.yaml
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/common.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/template/cephfs/csi-cephfsplugin-provisioner-dep.yaml
  pkg/operator/ceph/csi/template/rbd/csi-rbdplugin-provisioner-dep.yaml
Labels: backport-release-1.17, backport-release-1.18

#16260 core: cleanup csi-related folders from /var/lib/rook during uninstall
  pkg/daemon/ceph/cleanup/hostpath.go
Labels: backport-release-1.17, backport-release-1.18

#16069 object: mark realm as default to avoid zone creation
  Documentation/CRDs/Object-Storage/ceph-object-realm-crd.md
  Documentation/CRDs/Object-Storage/ceph-object-store-crd.md
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/object/controller.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/object/realm/controller.go
Labels: backport-release-1.17, backport-release-1.18

#16249 mon: Failover mon immediately if node not exist
  PendingReleaseNotes.md
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/k8sutil/node.go
Labels: backport-release-1.18

#16269 csi: Create cephconnection CR with name of the cluster namespace
  pkg/operator/ceph/csi/ceph_connection.go
  pkg/operator/ceph/csi/ceph_connection_test.go
Labels: backport-release-1.18

#16227 core: rotate mirror daemon keys
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/rbd/config.go
  pkg/operator/ceph/cluster/rbd/controller.go
  pkg/operator/ceph/cluster/rbd/controller_test.go
  pkg/operator/ceph/cluster/rbd/mirror.go
Labels: cephx-rotation, backport-release-1.18

#16277 csi: use cluster namespace for cephConn
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/csi/ceph_connection.go
  pkg/operator/ceph/csi/config.go
  pkg/operator/ceph/csi/config_test.go
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: backport-release-1.18

#16289 external: user userID and userKey for rbd
  deploy/examples/import-external-cluster.sh
Labels: backport-release-1.17, backport-release-1.18

#16294 csi: update Kubernetes CSI-Addons sidecar to version 0.13.0
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  tests/scripts/csiaddons.sh
Labels: backport-release-1.18

#16295 csi: update csi-operator yaml to version v0.4.0
  deploy/examples/csi-operator.yaml
Labels: backport-release-1.18

#16070 core: option to override the ceph user name in cephClient CR
  pkg/operator/ceph/client/controller.go
  pkg/operator/ceph/client/controller_test.go
Labels: backport-release-1.18

#16329 pool: fix cephblockpool remove when related pool is already removed
  pkg/daemon/ceph/client/pool.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: backport-release-1.17, backport-release-1.18

#16346 CephX key rotation 1.18 cleanup
  Documentation/CRDs/specification.md
  Documentation/Storage-Configuration/Advanced/.pages
  Documentation/Storage-Configuration/Advanced/cephx-key-rotation.md
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_test.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/mgr/mgr.go
  pkg/operator/ceph/cluster/mgr/mgr_test.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
  pkg/operator/ceph/cluster/nodedaemon/keyring.go
  pkg/operator/ceph/cluster/nodedaemon/keyring_test.go
  pkg/operator/ceph/cluster/osd/osd.go
  pkg/operator/ceph/cluster/osd/osd_test.go
  pkg/operator/ceph/config/keyring/cephx.go
  pkg/operator/ceph/config/keyring/cephx_test.go
  pkg/operator/ceph/controller/mirror_peer.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
Labels: cephx-rotation, backport-release-1.18

#15915 doc: add design for cephx key rotation
  design/ceph/cephx-keyring-rotation.md
Labels: docs, design, skip-ci, cephx-rotation

#16396 csi: fix wrong use of daemon config for cephx status
  pkg/operator/ceph/csi/secrets.go
Labels: backport-release-1.18

#16399 csi: Set the cephfs kernel mount options when network encryption is enabled
  pkg/apis/ceph.rook.io/v1/cluster.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/controller/cluster_info.go
  pkg/operator/ceph/controller/cluster_info_test.go
  pkg/operator/ceph/csi/config.go
Labels: backport-release-1.18

#16405 csi: Set csi operator as default if no settings found
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/controller_test.go
  pkg/operator/ceph/csi/secrets.go
Labels: backport-release-1.18

#16381 csi: delete csi operator CR's when disabled
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/spec.go
Labels: backport-release-1.18
