Repository rook/rook, pull requests merged in 2025-07, with the labels that each got.

#16093 ci: fix typo in debug-ci input for tmate action
  .github/workflows/tmate_debug/action.yml
Labels: debug-ci

#16056 mon: Failover with host network must use different node
  pkg/operator/ceph/cluster/mon/health.go
  pkg/operator/ceph/cluster/mon/health_test.go
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/mon/mon_test.go
Labels: backport-release-1.17

#16135 helm(rook-ceph-cluster): add HTTPRoute for dashboard and objectstore
  Documentation/Helm-Charts/ceph-cluster-chart.md
  PendingReleaseNotes.md
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-httproute.yaml
  deploy/charts/rook-ceph-cluster/templates/httproute.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.17

#16133 multus: support copy file to cmd-proxy container for rgw zone set
  pkg/operator/ceph/object/admin.go
  pkg/util/exec/exec_pod.go
Labels: backport-release-1.17

#16157 csi: update ceph-csi to 3.14.2
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Ceph-CSI/ceph-csi-drivers.md
  Documentation/Storage-Configuration/Ceph-CSI/custom-images.md
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/images.txt
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util_test.go
Labels: backport-release-1.17

#16123 correct example resources
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.17

#16040 csi: automate CSI cephx key rotation
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/auth.go
  pkg/operator/ceph/cluster/cluster.go
  pkg/operator/ceph/cluster/cluster_external.go
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/csi/secrets.go
  pkg/operator/ceph/csi/secrets_test.go
  tests/scripts/collect-logs.sh
Labels: cephx-rotation

#16190 ci: fix the csi ceph user keys for external mode
  .github/workflows/canary-integration-test.yml
Labels: ci, cephx-rotation

#16201 core: improve cleanup of /var/lib/rook during cluster teardown
  pkg/daemon/ceph/cleanup/hostpath.go
Labels: backport-release-1.17

#16215 ci: Enable mergify to open backports and automerge for 1.18
  .mergify.yml
Labels: skip-ci
