Repository rook/rook, pull requests merged in 2025-02, with the labels that each got.

#15393 nfs: workaround broken nfs-ganesha config parser
  pkg/operator/ceph/nfs/config.go
Labels: backport-release-1.15, backport-release-1.16

#15385 helm: add support for ingress path type
  deploy/charts/rook-ceph-cluster/templates/cephobjectstore-ingress.yaml
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
  deploy/charts/rook-ceph-cluster/values.yaml
Labels: backport-release-1.16

#15402 helm: Fix hardcoded namespace in cephECBlockPool StorageClass
  deploy/charts/rook-ceph-cluster/templates/cephecblockpool.yaml
Labels: backport-release-1.15, backport-release-1.16

#15372 helm: add support for custom pod labels in operator deployment config…
  Documentation/Helm-Charts/operator-chart.md
  deploy/charts/rook-ceph/templates/deployment.yaml
  deploy/charts/rook-ceph/values.yaml
Labels: backport-release-1.16

#15376 object: disallow unsafe OBC fields by default
  Documentation/Helm-Charts/operator-chart.md
  Documentation/Storage-Configuration/Object-Storage-RGW/ceph-object-bucket-claim.md
  deploy/charts/rook-ceph/templates/configmap.yaml
  deploy/charts/rook-ceph/values.yaml
  deploy/examples/operator-openshift.yaml
  deploy/examples/operator.yaml
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  tests/framework/installer/ceph_settings.go
Labels: backport-release-1.16

#15429 doc: add obc allow list to pending release notes
  PendingReleaseNotes.md
Labels: skip-ci

#15370 osd: Enable osd ok-to-stop checks on single node where there are at least three OSDs
  deploy/examples/cluster-test.yaml
  pkg/daemon/ceph/client/upgrade.go
  pkg/daemon/ceph/client/upgrade_test.go
Labels: backport-release-1.16

#15443 helm: quote object store ingress hostname
  deploy/charts/rook-ceph-cluster/templates/ingress.yaml
Labels: backport-release-1.16

#15442 core: Query env vars instead of polling the operator settings configmap
  deploy/examples/operator.yaml
  pkg/operator/ceph/cluster/controller.go
  pkg/operator/ceph/cluster/watcher.go
  pkg/operator/ceph/controller.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/controller_test.go
  pkg/operator/ceph/cr_manager.go
  pkg/operator/ceph/csi/controller.go
  pkg/operator/ceph/csi/csi.go
  pkg/operator/ceph/csi/operator_config.go
  pkg/operator/ceph/csi/operator_driver.go
  pkg/operator/ceph/csi/spec.go
  pkg/operator/ceph/csi/util.go
  pkg/operator/ceph/csi/util_test.go
  pkg/operator/ceph/object/bucket/controller.go
  pkg/operator/ceph/object/bucket/provisioner_test.go
  pkg/operator/ceph/object/bucket/util.go
  pkg/operator/ceph/object/objectstore.go
  pkg/operator/ceph/object/objectstore_test.go
  pkg/operator/ceph/operator.go
  pkg/operator/discover/discover.go
  pkg/operator/discover/discover_test.go
  pkg/operator/k8sutil/configmap.go
  pkg/operator/k8sutil/configmap_test.go
Labels: backport-release-1.16

#15455 docs: add comprehensive Rook Ceph cluster maintenance guide
  Documentation/Upgrade/node-maintenance.md
Labels: backport-release-1.16

#15470 mgr: Wait for builtin mgr pool to exist before enabling stretch
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/controller/controller_utils.go
  pkg/operator/ceph/controller/controller_utils_test.go
  pkg/operator/ceph/file/controller_test.go
Labels: backport-release-1.16

#15295 ci: Increase rgw multisite test timeout for s3 client call
  .github/workflows/canary-integration-test.yml
  tests/scripts/github-action-helper.sh
Labels: backport-release-1.16
