Repository rook/rook, pull requests merged in 2025-05, with the labels that each got.

#15781 build: add a script for setting the release version in examples, charts, and docs
  build/release/README.md
  tests/scripts/set-release-ver.sh
Labels: skip-ci, backport-release-1.16, backport-release-1.17

#15830 ci: Only publish docs in master and tagged releases
  build/release/Makefile
Labels: skip-ci, backport-release-1.17

#15683 ci: add a checkmake workflow
  .github/workflows/checkmake.yaml
Labels: skip-ci

#15817 block: Add more deletion conditions to blockpool and radosnamespace status
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/namespace.go
  pkg/apis/ceph.rook.io/v1/pool.go
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
  pkg/daemon/ceph/client/pool.go
  pkg/daemon/ceph/client/radosnamespace.go
  pkg/operator/ceph/pool/controller.go
  pkg/operator/ceph/pool/controller_test.go
  pkg/operator/ceph/pool/dependents.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller_test.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/status.go
  pkg/operator/ceph/reporting/status_test.go
  pkg/util/dependents/dependents.go
Labels: backport-release-1.17

#15829 object: change `CephObjectStore "foo" found` log level to debug
  pkg/operator/ceph/object/user/controller.go
Labels: backport-release-1.17

#15835 Revert "ci: only publish docs in master and tagged releases"
  build/release/Makefile
Labels: skip-ci, backport-release-1.17

#15842 network/provider-validation-rule-fix
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.17

#15851 ci: update mergify to latest k8s 1.33.0
  .mergify.yml
Labels: backport-release-1.17

#15858 rbdmirror: fix mirroring status on pool and rn
  Documentation/CRDs/specification.md
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/apis/ceph.rook.io/v1/zz_generated.deepcopy.go
  pkg/daemon/ceph/client/mirror.go
Labels: backport-release-1.17

#15824 osd: osd should watch for pvc resize
  pkg/operator/ceph/cluster/mon/mon.go
  pkg/operator/ceph/cluster/osd/deviceSet.go
  pkg/operator/ceph/cluster/osd/deviceset_test.go
  pkg/operator/k8sutil/pvc.go
  pkg/operator/k8sutil/pvc_test.go
Labels: backport-release-1.17

#15862 mgr: Continue cluster reconcile even if prometheus not installed causing service monitor to fail creation
  pkg/operator/ceph/cluster/mgr/mgr.go
Labels: backport-release-1.17

#15853 core: delete old svg/rns cr with same svg/rns name
  pkg/operator/ceph/file/subvolumegroup/controller.go
  pkg/operator/ceph/pool/radosnamespace/controller.go
Labels: backport-release-1.17

#15884 core: improve reporting for reconcile requeue cases
  Documentation/CRDs/specification.md
  pkg/apis/ceph.rook.io/v1/types.go
  pkg/operator/ceph/reporting/reporting.go
  pkg/operator/ceph/reporting/reporting_test.go
Labels: backport-release-1.17

#15888 core: add short names to rook CRDs
  deploy/charts/rook-ceph/templates/resources.yaml
  deploy/examples/crds.yaml
  pkg/apis/ceph.rook.io/v1/types.go
Labels: backport-release-1.17

#15887 osd: Debug log for long image names in label
  pkg/operator/ceph/cluster/osd/deviceSet.go
Labels: backport-release-1.17
